package ngo.nabarun.application;
import ngo.nabarun.common.props.PropertyKey;

public enum AppKeys implements PropertyKey{
	ENVIRONMENT,
	ENABLE_TOKEN_MOCKING_FOR_TEST,
	GOOGLE_CLIENT_SECRET,
	AUTH0_MANAGEMENT_CLIENT_ID,
	MONGODB_URL,
	APP_NAME,
	APP_SECRET,
	SENDGRID_SENDER_ADDRESS,
	GOOGLE_RECAPTCHA_SITE_KEY,
	AUTH0_BASE_URL,
	CORS_ALLOWED_ORIGIN,
	GITHUB_DICUSSION_ID,
	GITHUB_REPO,
	REDIS_PORT,
	FIREBASE_DATABASE_URL,
	REDIS_DATABASE,
	REDIS_PASSWORD,
	REDIS_TIMEOUT,
	MOCKED_EMAIL_ADDRESS,
	ENABLE_PROD_MODE_FOR_TEST,
	LOG_LEVEL,
	AUTH0_MANAGEMENT_API_AUDIENCE,
	SPRINGDOC_API_DOCS_ENABLED,
	DOPPLER_CONFIG,
	FIREBASE_FILESTORAGE_BUCKET,
	GOOGLE_CLIENT_ID,
	SENDGRID_API_KEY,
	RESTTIMEOUT_IN_SEC,
	APP_LOGIN_URL,
	GITHUB_TOKEN,
	CORS_ALLOWED_METHODS,
	AUTH0_ISSUER_URI,
	GOOGLE_RECAPTCHA_SECURITY_KEY,
	REDIS_SERVER,
	AUTH0_MANAGEMENT_CLIENT_SECRET,
	CONFLUENCE_APIKEY,
	ENABLE_EMAIL_MOCKING_FOR_TEST,
	MOCKED_TOKEN_USER_ID,
	DOPPLER_ENVIRONMENT,
	GITHUB_ORG,
	SENDGRID_DEFAULT_TEMPLATE_ID,
	INCLUDE_ERROR_DETAILS,
	FIREBASE_CREDENTIAL,
	REDIS_TTL,
	REDIS_USERNAME,
	AUTH0_RESOURCE_API_AUDIENCE,
	DOPPLER_PROJECT;

	@Override
	public String key() {
		return this.name();
	}

}
