runtime: java17
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_idle_instances: 0
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
env_variables:
  JAVA_OPTS: "-Xms256m -Xmx256m"
  ENVIRONMENT: $ENVIRONMENT
  DOPPLER_PROJECT_NAME: $DOPPLER_PROJECT_NAME
  DOPPLER_SERVICE_TOKEN: $DOPPLER_SERVICE_TOKEN
  LOG_LEVEL: $LOG_LEVEL
  
