
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccountBankInvestDetail` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AccountBankInvestDetail
 * 
 */
export type AccountBankInvestDetailModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountBankInvestDetailPayload>

export type AggregateAccountBankInvestDetail = {
  _count: AccountBankInvestDetailCountAggregateOutputType | null
  _avg: AccountBankInvestDetailAvgAggregateOutputType | null
  _sum: AccountBankInvestDetailSumAggregateOutputType | null
  _min: AccountBankInvestDetailMinAggregateOutputType | null
  _max: AccountBankInvestDetailMaxAggregateOutputType | null
}

export type AccountBankInvestDetailAvgAggregateOutputType = {
  maturityAmount: runtime.Decimal | null
  investmentAmount: runtime.Decimal | null
  interestRate: runtime.Decimal | null
}

export type AccountBankInvestDetailSumAggregateOutputType = {
  maturityAmount: runtime.Decimal | null
  investmentAmount: runtime.Decimal | null
  interestRate: runtime.Decimal | null
}

export type AccountBankInvestDetailMinAggregateOutputType = {
  id: string | null
  accountId: string | null
  bankAccountHolderName: string | null
  bankName: string | null
  bankBranch: string | null
  bankAccountNumber: string | null
  bankAccountType: string | null
  IFSCNumber: string | null
  maturityDate: Date | null
  maturityAmount: runtime.Decimal | null
  investmentAmount: runtime.Decimal | null
  sourceAccountId: string | null
  dematId: string | null
  interestRate: runtime.Decimal | null
  interestPayingTerm: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountBankInvestDetailMaxAggregateOutputType = {
  id: string | null
  accountId: string | null
  bankAccountHolderName: string | null
  bankName: string | null
  bankBranch: string | null
  bankAccountNumber: string | null
  bankAccountType: string | null
  IFSCNumber: string | null
  maturityDate: Date | null
  maturityAmount: runtime.Decimal | null
  investmentAmount: runtime.Decimal | null
  sourceAccountId: string | null
  dematId: string | null
  interestRate: runtime.Decimal | null
  interestPayingTerm: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountBankInvestDetailCountAggregateOutputType = {
  id: number
  accountId: number
  bankAccountHolderName: number
  bankName: number
  bankBranch: number
  bankAccountNumber: number
  bankAccountType: number
  IFSCNumber: number
  maturityDate: number
  maturityAmount: number
  investmentAmount: number
  sourceAccountId: number
  dematId: number
  interestRate: number
  interestPayingTerm: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccountBankInvestDetailAvgAggregateInputType = {
  maturityAmount?: true
  investmentAmount?: true
  interestRate?: true
}

export type AccountBankInvestDetailSumAggregateInputType = {
  maturityAmount?: true
  investmentAmount?: true
  interestRate?: true
}

export type AccountBankInvestDetailMinAggregateInputType = {
  id?: true
  accountId?: true
  bankAccountHolderName?: true
  bankName?: true
  bankBranch?: true
  bankAccountNumber?: true
  bankAccountType?: true
  IFSCNumber?: true
  maturityDate?: true
  maturityAmount?: true
  investmentAmount?: true
  sourceAccountId?: true
  dematId?: true
  interestRate?: true
  interestPayingTerm?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountBankInvestDetailMaxAggregateInputType = {
  id?: true
  accountId?: true
  bankAccountHolderName?: true
  bankName?: true
  bankBranch?: true
  bankAccountNumber?: true
  bankAccountType?: true
  IFSCNumber?: true
  maturityDate?: true
  maturityAmount?: true
  investmentAmount?: true
  sourceAccountId?: true
  dematId?: true
  interestRate?: true
  interestPayingTerm?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountBankInvestDetailCountAggregateInputType = {
  id?: true
  accountId?: true
  bankAccountHolderName?: true
  bankName?: true
  bankBranch?: true
  bankAccountNumber?: true
  bankAccountType?: true
  IFSCNumber?: true
  maturityDate?: true
  maturityAmount?: true
  investmentAmount?: true
  sourceAccountId?: true
  dematId?: true
  interestRate?: true
  interestPayingTerm?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccountBankInvestDetailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountBankInvestDetail to aggregate.
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountBankInvestDetails to fetch.
   */
  orderBy?: Prisma.AccountBankInvestDetailOrderByWithRelationInput | Prisma.AccountBankInvestDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountBankInvestDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountBankInvestDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountBankInvestDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccountBankInvestDetails
  **/
  _count?: true | AccountBankInvestDetailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountBankInvestDetailAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountBankInvestDetailSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountBankInvestDetailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountBankInvestDetailMaxAggregateInputType
}

export type GetAccountBankInvestDetailAggregateType<T extends AccountBankInvestDetailAggregateArgs> = {
      [P in keyof T & keyof AggregateAccountBankInvestDetail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccountBankInvestDetail[P]>
    : Prisma.GetScalarType<T[P], AggregateAccountBankInvestDetail[P]>
}




export type AccountBankInvestDetailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountBankInvestDetailWhereInput
  orderBy?: Prisma.AccountBankInvestDetailOrderByWithAggregationInput | Prisma.AccountBankInvestDetailOrderByWithAggregationInput[]
  by: Prisma.AccountBankInvestDetailScalarFieldEnum[] | Prisma.AccountBankInvestDetailScalarFieldEnum
  having?: Prisma.AccountBankInvestDetailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountBankInvestDetailCountAggregateInputType | true
  _avg?: AccountBankInvestDetailAvgAggregateInputType
  _sum?: AccountBankInvestDetailSumAggregateInputType
  _min?: AccountBankInvestDetailMinAggregateInputType
  _max?: AccountBankInvestDetailMaxAggregateInputType
}

export type AccountBankInvestDetailGroupByOutputType = {
  id: string
  accountId: string
  bankAccountHolderName: string | null
  bankName: string | null
  bankBranch: string | null
  bankAccountNumber: string | null
  bankAccountType: string | null
  IFSCNumber: string | null
  maturityDate: Date | null
  maturityAmount: runtime.Decimal | null
  investmentAmount: runtime.Decimal | null
  sourceAccountId: string | null
  dematId: string | null
  interestRate: runtime.Decimal | null
  interestPayingTerm: string | null
  createdAt: Date
  updatedAt: Date
  _count: AccountBankInvestDetailCountAggregateOutputType | null
  _avg: AccountBankInvestDetailAvgAggregateOutputType | null
  _sum: AccountBankInvestDetailSumAggregateOutputType | null
  _min: AccountBankInvestDetailMinAggregateOutputType | null
  _max: AccountBankInvestDetailMaxAggregateOutputType | null
}

export type GetAccountBankInvestDetailGroupByPayload<T extends AccountBankInvestDetailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountBankInvestDetailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountBankInvestDetailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountBankInvestDetailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountBankInvestDetailGroupByOutputType[P]>
      }
    >
  >



export type AccountBankInvestDetailWhereInput = {
  AND?: Prisma.AccountBankInvestDetailWhereInput | Prisma.AccountBankInvestDetailWhereInput[]
  OR?: Prisma.AccountBankInvestDetailWhereInput[]
  NOT?: Prisma.AccountBankInvestDetailWhereInput | Prisma.AccountBankInvestDetailWhereInput[]
  id?: Prisma.StringFilter<"AccountBankInvestDetail"> | string
  accountId?: Prisma.StringFilter<"AccountBankInvestDetail"> | string
  bankAccountHolderName?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankName?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankBranch?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankAccountNumber?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankAccountType?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  IFSCNumber?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  maturityDate?: Prisma.DateTimeNullableFilter<"AccountBankInvestDetail"> | Date | string | null
  maturityAmount?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  dematId?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  interestRate?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccountBankInvestDetail"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountBankInvestDetail"> | Date | string
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  sourceAccount?: Prisma.XOR<Prisma.AccountNullableScalarRelationFilter, Prisma.AccountWhereInput> | null
}

export type AccountBankInvestDetailOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  bankAccountHolderName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankBranch?: Prisma.SortOrderInput | Prisma.SortOrder
  bankAccountNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  bankAccountType?: Prisma.SortOrderInput | Prisma.SortOrder
  IFSCNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  maturityDate?: Prisma.SortOrderInput | Prisma.SortOrder
  maturityAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  investmentAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceAccountId?: Prisma.SortOrderInput | Prisma.SortOrder
  dematId?: Prisma.SortOrderInput | Prisma.SortOrder
  interestRate?: Prisma.SortOrderInput | Prisma.SortOrder
  interestPayingTerm?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  account?: Prisma.AccountOrderByWithRelationInput
  sourceAccount?: Prisma.AccountOrderByWithRelationInput
}

export type AccountBankInvestDetailWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  accountId?: string
  AND?: Prisma.AccountBankInvestDetailWhereInput | Prisma.AccountBankInvestDetailWhereInput[]
  OR?: Prisma.AccountBankInvestDetailWhereInput[]
  NOT?: Prisma.AccountBankInvestDetailWhereInput | Prisma.AccountBankInvestDetailWhereInput[]
  bankAccountHolderName?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankName?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankBranch?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankAccountNumber?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankAccountType?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  IFSCNumber?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  maturityDate?: Prisma.DateTimeNullableFilter<"AccountBankInvestDetail"> | Date | string | null
  maturityAmount?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  dematId?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  interestRate?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccountBankInvestDetail"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountBankInvestDetail"> | Date | string
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  sourceAccount?: Prisma.XOR<Prisma.AccountNullableScalarRelationFilter, Prisma.AccountWhereInput> | null
}, "id" | "accountId">

export type AccountBankInvestDetailOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  bankAccountHolderName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankBranch?: Prisma.SortOrderInput | Prisma.SortOrder
  bankAccountNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  bankAccountType?: Prisma.SortOrderInput | Prisma.SortOrder
  IFSCNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  maturityDate?: Prisma.SortOrderInput | Prisma.SortOrder
  maturityAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  investmentAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceAccountId?: Prisma.SortOrderInput | Prisma.SortOrder
  dematId?: Prisma.SortOrderInput | Prisma.SortOrder
  interestRate?: Prisma.SortOrderInput | Prisma.SortOrder
  interestPayingTerm?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccountBankInvestDetailCountOrderByAggregateInput
  _avg?: Prisma.AccountBankInvestDetailAvgOrderByAggregateInput
  _max?: Prisma.AccountBankInvestDetailMaxOrderByAggregateInput
  _min?: Prisma.AccountBankInvestDetailMinOrderByAggregateInput
  _sum?: Prisma.AccountBankInvestDetailSumOrderByAggregateInput
}

export type AccountBankInvestDetailScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountBankInvestDetailScalarWhereWithAggregatesInput | Prisma.AccountBankInvestDetailScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountBankInvestDetailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountBankInvestDetailScalarWhereWithAggregatesInput | Prisma.AccountBankInvestDetailScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AccountBankInvestDetail"> | string
  accountId?: Prisma.StringWithAggregatesFilter<"AccountBankInvestDetail"> | string
  bankAccountHolderName?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  bankName?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  bankBranch?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  bankAccountNumber?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  bankAccountType?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  IFSCNumber?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  maturityDate?: Prisma.DateTimeNullableWithAggregatesFilter<"AccountBankInvestDetail"> | Date | string | null
  maturityAmount?: Prisma.DecimalNullableWithAggregatesFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.DecimalNullableWithAggregatesFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  dematId?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  interestRate?: Prisma.DecimalNullableWithAggregatesFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.StringNullableWithAggregatesFilter<"AccountBankInvestDetail"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccountBankInvestDetail"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccountBankInvestDetail"> | Date | string
}

export type AccountBankInvestDetailCreateInput = {
  id?: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.AccountCreateNestedOneWithoutBankInvestDetailInput
  sourceAccount?: Prisma.AccountCreateNestedOneWithoutFundedInvestmentsInput
}

export type AccountBankInvestDetailUncheckedCreateInput = {
  id?: string
  accountId: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountBankInvestDetailUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.AccountUpdateOneRequiredWithoutBankInvestDetailNestedInput
  sourceAccount?: Prisma.AccountUpdateOneWithoutFundedInvestmentsNestedInput
}

export type AccountBankInvestDetailUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountBankInvestDetailCreateManyInput = {
  id?: string
  accountId: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountBankInvestDetailUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountBankInvestDetailUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountBankInvestDetailNullableScalarRelationFilter = {
  is?: Prisma.AccountBankInvestDetailWhereInput | null
  isNot?: Prisma.AccountBankInvestDetailWhereInput | null
}

export type AccountBankInvestDetailListRelationFilter = {
  every?: Prisma.AccountBankInvestDetailWhereInput
  some?: Prisma.AccountBankInvestDetailWhereInput
  none?: Prisma.AccountBankInvestDetailWhereInput
}

export type AccountBankInvestDetailOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccountBankInvestDetailCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  bankAccountHolderName?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  bankBranch?: Prisma.SortOrder
  bankAccountNumber?: Prisma.SortOrder
  bankAccountType?: Prisma.SortOrder
  IFSCNumber?: Prisma.SortOrder
  maturityDate?: Prisma.SortOrder
  maturityAmount?: Prisma.SortOrder
  investmentAmount?: Prisma.SortOrder
  sourceAccountId?: Prisma.SortOrder
  dematId?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  interestPayingTerm?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountBankInvestDetailAvgOrderByAggregateInput = {
  maturityAmount?: Prisma.SortOrder
  investmentAmount?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
}

export type AccountBankInvestDetailMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  bankAccountHolderName?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  bankBranch?: Prisma.SortOrder
  bankAccountNumber?: Prisma.SortOrder
  bankAccountType?: Prisma.SortOrder
  IFSCNumber?: Prisma.SortOrder
  maturityDate?: Prisma.SortOrder
  maturityAmount?: Prisma.SortOrder
  investmentAmount?: Prisma.SortOrder
  sourceAccountId?: Prisma.SortOrder
  dematId?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  interestPayingTerm?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountBankInvestDetailMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  bankAccountHolderName?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  bankBranch?: Prisma.SortOrder
  bankAccountNumber?: Prisma.SortOrder
  bankAccountType?: Prisma.SortOrder
  IFSCNumber?: Prisma.SortOrder
  maturityDate?: Prisma.SortOrder
  maturityAmount?: Prisma.SortOrder
  investmentAmount?: Prisma.SortOrder
  sourceAccountId?: Prisma.SortOrder
  dematId?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
  interestPayingTerm?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountBankInvestDetailSumOrderByAggregateInput = {
  maturityAmount?: Prisma.SortOrder
  investmentAmount?: Prisma.SortOrder
  interestRate?: Prisma.SortOrder
}

export type AccountBankInvestDetailCreateNestedOneWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutAccountInput>
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutAccountInput
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput
}

export type AccountBankInvestDetailCreateNestedManyWithoutSourceAccountInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput> | Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput[] | Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput[]
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput | Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput[]
  createMany?: Prisma.AccountBankInvestDetailCreateManySourceAccountInputEnvelope
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
}

export type AccountBankInvestDetailUncheckedCreateNestedOneWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutAccountInput>
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutAccountInput
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput
}

export type AccountBankInvestDetailUncheckedCreateNestedManyWithoutSourceAccountInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput> | Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput[] | Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput[]
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput | Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput[]
  createMany?: Prisma.AccountBankInvestDetailCreateManySourceAccountInputEnvelope
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
}

export type AccountBankInvestDetailUpdateOneWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutAccountInput>
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutAccountInput
  upsert?: Prisma.AccountBankInvestDetailUpsertWithoutAccountInput
  disconnect?: Prisma.AccountBankInvestDetailWhereInput | boolean
  delete?: Prisma.AccountBankInvestDetailWhereInput | boolean
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountBankInvestDetailUpdateToOneWithWhereWithoutAccountInput, Prisma.AccountBankInvestDetailUpdateWithoutAccountInput>, Prisma.AccountBankInvestDetailUncheckedUpdateWithoutAccountInput>
}

export type AccountBankInvestDetailUpdateManyWithoutSourceAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput> | Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput[] | Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput[]
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput | Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput[]
  upsert?: Prisma.AccountBankInvestDetailUpsertWithWhereUniqueWithoutSourceAccountInput | Prisma.AccountBankInvestDetailUpsertWithWhereUniqueWithoutSourceAccountInput[]
  createMany?: Prisma.AccountBankInvestDetailCreateManySourceAccountInputEnvelope
  set?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  disconnect?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  delete?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  update?: Prisma.AccountBankInvestDetailUpdateWithWhereUniqueWithoutSourceAccountInput | Prisma.AccountBankInvestDetailUpdateWithWhereUniqueWithoutSourceAccountInput[]
  updateMany?: Prisma.AccountBankInvestDetailUpdateManyWithWhereWithoutSourceAccountInput | Prisma.AccountBankInvestDetailUpdateManyWithWhereWithoutSourceAccountInput[]
  deleteMany?: Prisma.AccountBankInvestDetailScalarWhereInput | Prisma.AccountBankInvestDetailScalarWhereInput[]
}

export type AccountBankInvestDetailUncheckedUpdateOneWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutAccountInput>
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutAccountInput
  upsert?: Prisma.AccountBankInvestDetailUpsertWithoutAccountInput
  disconnect?: Prisma.AccountBankInvestDetailWhereInput | boolean
  delete?: Prisma.AccountBankInvestDetailWhereInput | boolean
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountBankInvestDetailUpdateToOneWithWhereWithoutAccountInput, Prisma.AccountBankInvestDetailUpdateWithoutAccountInput>, Prisma.AccountBankInvestDetailUncheckedUpdateWithoutAccountInput>
}

export type AccountBankInvestDetailUncheckedUpdateManyWithoutSourceAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput> | Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput[] | Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput[]
  connectOrCreate?: Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput | Prisma.AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput[]
  upsert?: Prisma.AccountBankInvestDetailUpsertWithWhereUniqueWithoutSourceAccountInput | Prisma.AccountBankInvestDetailUpsertWithWhereUniqueWithoutSourceAccountInput[]
  createMany?: Prisma.AccountBankInvestDetailCreateManySourceAccountInputEnvelope
  set?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  disconnect?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  delete?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  connect?: Prisma.AccountBankInvestDetailWhereUniqueInput | Prisma.AccountBankInvestDetailWhereUniqueInput[]
  update?: Prisma.AccountBankInvestDetailUpdateWithWhereUniqueWithoutSourceAccountInput | Prisma.AccountBankInvestDetailUpdateWithWhereUniqueWithoutSourceAccountInput[]
  updateMany?: Prisma.AccountBankInvestDetailUpdateManyWithWhereWithoutSourceAccountInput | Prisma.AccountBankInvestDetailUpdateManyWithWhereWithoutSourceAccountInput[]
  deleteMany?: Prisma.AccountBankInvestDetailScalarWhereInput | Prisma.AccountBankInvestDetailScalarWhereInput[]
}

export type AccountBankInvestDetailCreateWithoutAccountInput = {
  id?: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sourceAccount?: Prisma.AccountCreateNestedOneWithoutFundedInvestmentsInput
}

export type AccountBankInvestDetailUncheckedCreateWithoutAccountInput = {
  id?: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountBankInvestDetailCreateOrConnectWithoutAccountInput = {
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutAccountInput>
}

export type AccountBankInvestDetailCreateWithoutSourceAccountInput = {
  id?: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.AccountCreateNestedOneWithoutBankInvestDetailInput
}

export type AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput = {
  id?: string
  accountId: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountBankInvestDetailCreateOrConnectWithoutSourceAccountInput = {
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput>
}

export type AccountBankInvestDetailCreateManySourceAccountInputEnvelope = {
  data: Prisma.AccountBankInvestDetailCreateManySourceAccountInput | Prisma.AccountBankInvestDetailCreateManySourceAccountInput[]
  skipDuplicates?: boolean
}

export type AccountBankInvestDetailUpsertWithoutAccountInput = {
  update: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutAccountInput>
  where?: Prisma.AccountBankInvestDetailWhereInput
}

export type AccountBankInvestDetailUpdateToOneWithWhereWithoutAccountInput = {
  where?: Prisma.AccountBankInvestDetailWhereInput
  data: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateWithoutAccountInput, Prisma.AccountBankInvestDetailUncheckedUpdateWithoutAccountInput>
}

export type AccountBankInvestDetailUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sourceAccount?: Prisma.AccountUpdateOneWithoutFundedInvestmentsNestedInput
}

export type AccountBankInvestDetailUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountBankInvestDetailUpsertWithWhereUniqueWithoutSourceAccountInput = {
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedUpdateWithoutSourceAccountInput>
  create: Prisma.XOR<Prisma.AccountBankInvestDetailCreateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedCreateWithoutSourceAccountInput>
}

export type AccountBankInvestDetailUpdateWithWhereUniqueWithoutSourceAccountInput = {
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateWithoutSourceAccountInput, Prisma.AccountBankInvestDetailUncheckedUpdateWithoutSourceAccountInput>
}

export type AccountBankInvestDetailUpdateManyWithWhereWithoutSourceAccountInput = {
  where: Prisma.AccountBankInvestDetailScalarWhereInput
  data: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateManyMutationInput, Prisma.AccountBankInvestDetailUncheckedUpdateManyWithoutSourceAccountInput>
}

export type AccountBankInvestDetailScalarWhereInput = {
  AND?: Prisma.AccountBankInvestDetailScalarWhereInput | Prisma.AccountBankInvestDetailScalarWhereInput[]
  OR?: Prisma.AccountBankInvestDetailScalarWhereInput[]
  NOT?: Prisma.AccountBankInvestDetailScalarWhereInput | Prisma.AccountBankInvestDetailScalarWhereInput[]
  id?: Prisma.StringFilter<"AccountBankInvestDetail"> | string
  accountId?: Prisma.StringFilter<"AccountBankInvestDetail"> | string
  bankAccountHolderName?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankName?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankBranch?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankAccountNumber?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  bankAccountType?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  IFSCNumber?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  maturityDate?: Prisma.DateTimeNullableFilter<"AccountBankInvestDetail"> | Date | string | null
  maturityAmount?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  sourceAccountId?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  dematId?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  interestRate?: Prisma.DecimalNullableFilter<"AccountBankInvestDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.StringNullableFilter<"AccountBankInvestDetail"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccountBankInvestDetail"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountBankInvestDetail"> | Date | string
}

export type AccountBankInvestDetailCreateManySourceAccountInput = {
  id?: string
  accountId: string
  bankAccountHolderName?: string | null
  bankName?: string | null
  bankBranch?: string | null
  bankAccountNumber?: string | null
  bankAccountType?: string | null
  IFSCNumber?: string | null
  maturityDate?: Date | string | null
  maturityAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: string | null
  interestRate?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountBankInvestDetailUpdateWithoutSourceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.AccountUpdateOneRequiredWithoutBankInvestDetailNestedInput
}

export type AccountBankInvestDetailUncheckedUpdateWithoutSourceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountBankInvestDetailUncheckedUpdateManyWithoutSourceAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  bankAccountHolderName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankBranch?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccountType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IFSCNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  maturityDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  maturityAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  investmentAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  dematId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestRate?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  interestPayingTerm?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AccountBankInvestDetailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  bankAccountHolderName?: boolean
  bankName?: boolean
  bankBranch?: boolean
  bankAccountNumber?: boolean
  bankAccountType?: boolean
  IFSCNumber?: boolean
  maturityDate?: boolean
  maturityAmount?: boolean
  investmentAmount?: boolean
  sourceAccountId?: boolean
  dematId?: boolean
  interestRate?: boolean
  interestPayingTerm?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  sourceAccount?: boolean | Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>
}, ExtArgs["result"]["accountBankInvestDetail"]>

export type AccountBankInvestDetailSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  bankAccountHolderName?: boolean
  bankName?: boolean
  bankBranch?: boolean
  bankAccountNumber?: boolean
  bankAccountType?: boolean
  IFSCNumber?: boolean
  maturityDate?: boolean
  maturityAmount?: boolean
  investmentAmount?: boolean
  sourceAccountId?: boolean
  dematId?: boolean
  interestRate?: boolean
  interestPayingTerm?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  sourceAccount?: boolean | Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>
}, ExtArgs["result"]["accountBankInvestDetail"]>

export type AccountBankInvestDetailSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  bankAccountHolderName?: boolean
  bankName?: boolean
  bankBranch?: boolean
  bankAccountNumber?: boolean
  bankAccountType?: boolean
  IFSCNumber?: boolean
  maturityDate?: boolean
  maturityAmount?: boolean
  investmentAmount?: boolean
  sourceAccountId?: boolean
  dematId?: boolean
  interestRate?: boolean
  interestPayingTerm?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  sourceAccount?: boolean | Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>
}, ExtArgs["result"]["accountBankInvestDetail"]>

export type AccountBankInvestDetailSelectScalar = {
  id?: boolean
  accountId?: boolean
  bankAccountHolderName?: boolean
  bankName?: boolean
  bankBranch?: boolean
  bankAccountNumber?: boolean
  bankAccountType?: boolean
  IFSCNumber?: boolean
  maturityDate?: boolean
  maturityAmount?: boolean
  investmentAmount?: boolean
  sourceAccountId?: boolean
  dematId?: boolean
  interestRate?: boolean
  interestPayingTerm?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccountBankInvestDetailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accountId" | "bankAccountHolderName" | "bankName" | "bankBranch" | "bankAccountNumber" | "bankAccountType" | "IFSCNumber" | "maturityDate" | "maturityAmount" | "investmentAmount" | "sourceAccountId" | "dematId" | "interestRate" | "interestPayingTerm" | "createdAt" | "updatedAt", ExtArgs["result"]["accountBankInvestDetail"]>
export type AccountBankInvestDetailInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  sourceAccount?: boolean | Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>
}
export type AccountBankInvestDetailIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  sourceAccount?: boolean | Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>
}
export type AccountBankInvestDetailIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  sourceAccount?: boolean | Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>
}

export type $AccountBankInvestDetailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccountBankInvestDetail"
  objects: {
    account: Prisma.$AccountPayload<ExtArgs>
    sourceAccount: Prisma.$AccountPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    accountId: string
    bankAccountHolderName: string | null
    bankName: string | null
    bankBranch: string | null
    bankAccountNumber: string | null
    bankAccountType: string | null
    IFSCNumber: string | null
    maturityDate: Date | null
    maturityAmount: runtime.Decimal | null
    investmentAmount: runtime.Decimal | null
    sourceAccountId: string | null
    dematId: string | null
    interestRate: runtime.Decimal | null
    interestPayingTerm: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accountBankInvestDetail"]>
  composites: {}
}

export type AccountBankInvestDetailGetPayload<S extends boolean | null | undefined | AccountBankInvestDetailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload, S>

export type AccountBankInvestDetailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountBankInvestDetailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountBankInvestDetailCountAggregateInputType | true
  }

export interface AccountBankInvestDetailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccountBankInvestDetail'], meta: { name: 'AccountBankInvestDetail' } }
  /**
   * Find zero or one AccountBankInvestDetail that matches the filter.
   * @param {AccountBankInvestDetailFindUniqueArgs} args - Arguments to find a AccountBankInvestDetail
   * @example
   * // Get one AccountBankInvestDetail
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountBankInvestDetailFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccountBankInvestDetail that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountBankInvestDetailFindUniqueOrThrowArgs} args - Arguments to find a AccountBankInvestDetail
   * @example
   * // Get one AccountBankInvestDetail
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountBankInvestDetailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountBankInvestDetail that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailFindFirstArgs} args - Arguments to find a AccountBankInvestDetail
   * @example
   * // Get one AccountBankInvestDetail
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountBankInvestDetailFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountBankInvestDetailFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountBankInvestDetail that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailFindFirstOrThrowArgs} args - Arguments to find a AccountBankInvestDetail
   * @example
   * // Get one AccountBankInvestDetail
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountBankInvestDetailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountBankInvestDetailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccountBankInvestDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccountBankInvestDetails
   * const accountBankInvestDetails = await prisma.accountBankInvestDetail.findMany()
   * 
   * // Get first 10 AccountBankInvestDetails
   * const accountBankInvestDetails = await prisma.accountBankInvestDetail.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountBankInvestDetailWithIdOnly = await prisma.accountBankInvestDetail.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountBankInvestDetailFindManyArgs>(args?: Prisma.SelectSubset<T, AccountBankInvestDetailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccountBankInvestDetail.
   * @param {AccountBankInvestDetailCreateArgs} args - Arguments to create a AccountBankInvestDetail.
   * @example
   * // Create one AccountBankInvestDetail
   * const AccountBankInvestDetail = await prisma.accountBankInvestDetail.create({
   *   data: {
   *     // ... data to create a AccountBankInvestDetail
   *   }
   * })
   * 
   */
  create<T extends AccountBankInvestDetailCreateArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailCreateArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccountBankInvestDetails.
   * @param {AccountBankInvestDetailCreateManyArgs} args - Arguments to create many AccountBankInvestDetails.
   * @example
   * // Create many AccountBankInvestDetails
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountBankInvestDetailCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountBankInvestDetailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccountBankInvestDetails and returns the data saved in the database.
   * @param {AccountBankInvestDetailCreateManyAndReturnArgs} args - Arguments to create many AccountBankInvestDetails.
   * @example
   * // Create many AccountBankInvestDetails
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccountBankInvestDetails and only return the `id`
   * const accountBankInvestDetailWithIdOnly = await prisma.accountBankInvestDetail.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountBankInvestDetailCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountBankInvestDetailCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccountBankInvestDetail.
   * @param {AccountBankInvestDetailDeleteArgs} args - Arguments to delete one AccountBankInvestDetail.
   * @example
   * // Delete one AccountBankInvestDetail
   * const AccountBankInvestDetail = await prisma.accountBankInvestDetail.delete({
   *   where: {
   *     // ... filter to delete one AccountBankInvestDetail
   *   }
   * })
   * 
   */
  delete<T extends AccountBankInvestDetailDeleteArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccountBankInvestDetail.
   * @param {AccountBankInvestDetailUpdateArgs} args - Arguments to update one AccountBankInvestDetail.
   * @example
   * // Update one AccountBankInvestDetail
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountBankInvestDetailUpdateArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccountBankInvestDetails.
   * @param {AccountBankInvestDetailDeleteManyArgs} args - Arguments to filter AccountBankInvestDetails to delete.
   * @example
   * // Delete a few AccountBankInvestDetails
   * const { count } = await prisma.accountBankInvestDetail.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountBankInvestDetailDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountBankInvestDetailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountBankInvestDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccountBankInvestDetails
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountBankInvestDetailUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountBankInvestDetails and returns the data updated in the database.
   * @param {AccountBankInvestDetailUpdateManyAndReturnArgs} args - Arguments to update many AccountBankInvestDetails.
   * @example
   * // Update many AccountBankInvestDetails
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccountBankInvestDetails and only return the `id`
   * const accountBankInvestDetailWithIdOnly = await prisma.accountBankInvestDetail.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountBankInvestDetailUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccountBankInvestDetail.
   * @param {AccountBankInvestDetailUpsertArgs} args - Arguments to update or create a AccountBankInvestDetail.
   * @example
   * // Update or create a AccountBankInvestDetail
   * const accountBankInvestDetail = await prisma.accountBankInvestDetail.upsert({
   *   create: {
   *     // ... data to create a AccountBankInvestDetail
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccountBankInvestDetail we want to update
   *   }
   * })
   */
  upsert<T extends AccountBankInvestDetailUpsertArgs>(args: Prisma.SelectSubset<T, AccountBankInvestDetailUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountBankInvestDetailClient<runtime.Types.Result.GetResult<Prisma.$AccountBankInvestDetailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccountBankInvestDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailCountArgs} args - Arguments to filter AccountBankInvestDetails to count.
   * @example
   * // Count the number of AccountBankInvestDetails
   * const count = await prisma.accountBankInvestDetail.count({
   *   where: {
   *     // ... the filter for the AccountBankInvestDetails we want to count
   *   }
   * })
  **/
  count<T extends AccountBankInvestDetailCountArgs>(
    args?: Prisma.Subset<T, AccountBankInvestDetailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountBankInvestDetailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccountBankInvestDetail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountBankInvestDetailAggregateArgs>(args: Prisma.Subset<T, AccountBankInvestDetailAggregateArgs>): Prisma.PrismaPromise<GetAccountBankInvestDetailAggregateType<T>>

  /**
   * Group by AccountBankInvestDetail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountBankInvestDetailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountBankInvestDetailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountBankInvestDetailGroupByArgs['orderBy'] }
      : { orderBy?: AccountBankInvestDetailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountBankInvestDetailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountBankInvestDetailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccountBankInvestDetail model
 */
readonly fields: AccountBankInvestDetailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccountBankInvestDetail.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountBankInvestDetailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  account<T extends Prisma.AccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sourceAccount<T extends Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountBankInvestDetail$sourceAccountArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccountBankInvestDetail model
 */
export interface AccountBankInvestDetailFieldRefs {
  readonly id: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly accountId: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly bankAccountHolderName: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly bankName: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly bankBranch: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly bankAccountNumber: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly bankAccountType: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly IFSCNumber: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly maturityDate: Prisma.FieldRef<"AccountBankInvestDetail", 'DateTime'>
  readonly maturityAmount: Prisma.FieldRef<"AccountBankInvestDetail", 'Decimal'>
  readonly investmentAmount: Prisma.FieldRef<"AccountBankInvestDetail", 'Decimal'>
  readonly sourceAccountId: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly dematId: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly interestRate: Prisma.FieldRef<"AccountBankInvestDetail", 'Decimal'>
  readonly interestPayingTerm: Prisma.FieldRef<"AccountBankInvestDetail", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccountBankInvestDetail", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccountBankInvestDetail", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccountBankInvestDetail findUnique
 */
export type AccountBankInvestDetailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * Filter, which AccountBankInvestDetail to fetch.
   */
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
}

/**
 * AccountBankInvestDetail findUniqueOrThrow
 */
export type AccountBankInvestDetailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * Filter, which AccountBankInvestDetail to fetch.
   */
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
}

/**
 * AccountBankInvestDetail findFirst
 */
export type AccountBankInvestDetailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * Filter, which AccountBankInvestDetail to fetch.
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountBankInvestDetails to fetch.
   */
  orderBy?: Prisma.AccountBankInvestDetailOrderByWithRelationInput | Prisma.AccountBankInvestDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountBankInvestDetails.
   */
  cursor?: Prisma.AccountBankInvestDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountBankInvestDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountBankInvestDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountBankInvestDetails.
   */
  distinct?: Prisma.AccountBankInvestDetailScalarFieldEnum | Prisma.AccountBankInvestDetailScalarFieldEnum[]
}

/**
 * AccountBankInvestDetail findFirstOrThrow
 */
export type AccountBankInvestDetailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * Filter, which AccountBankInvestDetail to fetch.
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountBankInvestDetails to fetch.
   */
  orderBy?: Prisma.AccountBankInvestDetailOrderByWithRelationInput | Prisma.AccountBankInvestDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountBankInvestDetails.
   */
  cursor?: Prisma.AccountBankInvestDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountBankInvestDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountBankInvestDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountBankInvestDetails.
   */
  distinct?: Prisma.AccountBankInvestDetailScalarFieldEnum | Prisma.AccountBankInvestDetailScalarFieldEnum[]
}

/**
 * AccountBankInvestDetail findMany
 */
export type AccountBankInvestDetailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * Filter, which AccountBankInvestDetails to fetch.
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountBankInvestDetails to fetch.
   */
  orderBy?: Prisma.AccountBankInvestDetailOrderByWithRelationInput | Prisma.AccountBankInvestDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccountBankInvestDetails.
   */
  cursor?: Prisma.AccountBankInvestDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountBankInvestDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountBankInvestDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountBankInvestDetails.
   */
  distinct?: Prisma.AccountBankInvestDetailScalarFieldEnum | Prisma.AccountBankInvestDetailScalarFieldEnum[]
}

/**
 * AccountBankInvestDetail create
 */
export type AccountBankInvestDetailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * The data needed to create a AccountBankInvestDetail.
   */
  data: Prisma.XOR<Prisma.AccountBankInvestDetailCreateInput, Prisma.AccountBankInvestDetailUncheckedCreateInput>
}

/**
 * AccountBankInvestDetail createMany
 */
export type AccountBankInvestDetailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccountBankInvestDetails.
   */
  data: Prisma.AccountBankInvestDetailCreateManyInput | Prisma.AccountBankInvestDetailCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccountBankInvestDetail createManyAndReturn
 */
export type AccountBankInvestDetailCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * The data used to create many AccountBankInvestDetails.
   */
  data: Prisma.AccountBankInvestDetailCreateManyInput | Prisma.AccountBankInvestDetailCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccountBankInvestDetail update
 */
export type AccountBankInvestDetailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * The data needed to update a AccountBankInvestDetail.
   */
  data: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateInput, Prisma.AccountBankInvestDetailUncheckedUpdateInput>
  /**
   * Choose, which AccountBankInvestDetail to update.
   */
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
}

/**
 * AccountBankInvestDetail updateMany
 */
export type AccountBankInvestDetailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccountBankInvestDetails.
   */
  data: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateManyMutationInput, Prisma.AccountBankInvestDetailUncheckedUpdateManyInput>
  /**
   * Filter which AccountBankInvestDetails to update
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * Limit how many AccountBankInvestDetails to update.
   */
  limit?: number
}

/**
 * AccountBankInvestDetail updateManyAndReturn
 */
export type AccountBankInvestDetailUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * The data used to update AccountBankInvestDetails.
   */
  data: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateManyMutationInput, Prisma.AccountBankInvestDetailUncheckedUpdateManyInput>
  /**
   * Filter which AccountBankInvestDetails to update
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * Limit how many AccountBankInvestDetails to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccountBankInvestDetail upsert
 */
export type AccountBankInvestDetailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * The filter to search for the AccountBankInvestDetail to update in case it exists.
   */
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
  /**
   * In case the AccountBankInvestDetail found by the `where` argument doesn't exist, create a new AccountBankInvestDetail with this data.
   */
  create: Prisma.XOR<Prisma.AccountBankInvestDetailCreateInput, Prisma.AccountBankInvestDetailUncheckedCreateInput>
  /**
   * In case the AccountBankInvestDetail was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountBankInvestDetailUpdateInput, Prisma.AccountBankInvestDetailUncheckedUpdateInput>
}

/**
 * AccountBankInvestDetail delete
 */
export type AccountBankInvestDetailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
  /**
   * Filter which AccountBankInvestDetail to delete.
   */
  where: Prisma.AccountBankInvestDetailWhereUniqueInput
}

/**
 * AccountBankInvestDetail deleteMany
 */
export type AccountBankInvestDetailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountBankInvestDetails to delete
   */
  where?: Prisma.AccountBankInvestDetailWhereInput
  /**
   * Limit how many AccountBankInvestDetails to delete.
   */
  limit?: number
}

/**
 * AccountBankInvestDetail.sourceAccount
 */
export type AccountBankInvestDetail$sourceAccountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  where?: Prisma.AccountWhereInput
}

/**
 * AccountBankInvestDetail without action
 */
export type AccountBankInvestDetailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountBankInvestDetail
   */
  select?: Prisma.AccountBankInvestDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountBankInvestDetail
   */
  omit?: Prisma.AccountBankInvestDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountBankInvestDetailInclude<ExtArgs> | null
}
