
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Donor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Donor
 * 
 */
export type DonorModel = runtime.Types.Result.DefaultSelection<Prisma.$DonorPayload>

export type AggregateDonor = {
  _count: DonorCountAggregateOutputType | null
  _avg: DonorAvgAggregateOutputType | null
  _sum: DonorSumAggregateOutputType | null
  _min: DonorMinAggregateOutputType | null
  _max: DonorMaxAggregateOutputType | null
}

export type DonorAvgAggregateOutputType = {
  preferredAmount: runtime.Decimal | null
  version: number | null
}

export type DonorSumAggregateOutputType = {
  preferredAmount: runtime.Decimal | null
  version: number | null
}

export type DonorMinAggregateOutputType = {
  id: string | null
  type: string | null
  status: string | null
  preferredAmount: runtime.Decimal | null
  statusEndDate: Date | null
  fullName: string | null
  email: string | null
  phoneCode: string | null
  phoneNumber: string | null
  userProfileId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  deletedAt: Date | null
}

export type DonorMaxAggregateOutputType = {
  id: string | null
  type: string | null
  status: string | null
  preferredAmount: runtime.Decimal | null
  statusEndDate: Date | null
  fullName: string | null
  email: string | null
  phoneCode: string | null
  phoneNumber: string | null
  userProfileId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  deletedAt: Date | null
}

export type DonorCountAggregateOutputType = {
  id: number
  type: number
  status: number
  preferredAmount: number
  statusEndDate: number
  fullName: number
  email: number
  phoneCode: number
  phoneNumber: number
  userProfileId: number
  createdAt: number
  updatedAt: number
  version: number
  deletedAt: number
  _all: number
}


export type DonorAvgAggregateInputType = {
  preferredAmount?: true
  version?: true
}

export type DonorSumAggregateInputType = {
  preferredAmount?: true
  version?: true
}

export type DonorMinAggregateInputType = {
  id?: true
  type?: true
  status?: true
  preferredAmount?: true
  statusEndDate?: true
  fullName?: true
  email?: true
  phoneCode?: true
  phoneNumber?: true
  userProfileId?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  deletedAt?: true
}

export type DonorMaxAggregateInputType = {
  id?: true
  type?: true
  status?: true
  preferredAmount?: true
  statusEndDate?: true
  fullName?: true
  email?: true
  phoneCode?: true
  phoneNumber?: true
  userProfileId?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  deletedAt?: true
}

export type DonorCountAggregateInputType = {
  id?: true
  type?: true
  status?: true
  preferredAmount?: true
  statusEndDate?: true
  fullName?: true
  email?: true
  phoneCode?: true
  phoneNumber?: true
  userProfileId?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  deletedAt?: true
  _all?: true
}

export type DonorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Donor to aggregate.
   */
  where?: Prisma.DonorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donors to fetch.
   */
  orderBy?: Prisma.DonorOrderByWithRelationInput | Prisma.DonorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DonorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Donors
  **/
  _count?: true | DonorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DonorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DonorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DonorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DonorMaxAggregateInputType
}

export type GetDonorAggregateType<T extends DonorAggregateArgs> = {
      [P in keyof T & keyof AggregateDonor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDonor[P]>
    : Prisma.GetScalarType<T[P], AggregateDonor[P]>
}




export type DonorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DonorWhereInput
  orderBy?: Prisma.DonorOrderByWithAggregationInput | Prisma.DonorOrderByWithAggregationInput[]
  by: Prisma.DonorScalarFieldEnum[] | Prisma.DonorScalarFieldEnum
  having?: Prisma.DonorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DonorCountAggregateInputType | true
  _avg?: DonorAvgAggregateInputType
  _sum?: DonorSumAggregateInputType
  _min?: DonorMinAggregateInputType
  _max?: DonorMaxAggregateInputType
}

export type DonorGroupByOutputType = {
  id: string
  type: string
  status: string
  preferredAmount: runtime.Decimal | null
  statusEndDate: Date | null
  fullName: string | null
  email: string | null
  phoneCode: string | null
  phoneNumber: string | null
  userProfileId: string | null
  createdAt: Date
  updatedAt: Date
  version: number
  deletedAt: Date | null
  _count: DonorCountAggregateOutputType | null
  _avg: DonorAvgAggregateOutputType | null
  _sum: DonorSumAggregateOutputType | null
  _min: DonorMinAggregateOutputType | null
  _max: DonorMaxAggregateOutputType | null
}

export type GetDonorGroupByPayload<T extends DonorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DonorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DonorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DonorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DonorGroupByOutputType[P]>
      }
    >
  >



export type DonorWhereInput = {
  AND?: Prisma.DonorWhereInput | Prisma.DonorWhereInput[]
  OR?: Prisma.DonorWhereInput[]
  NOT?: Prisma.DonorWhereInput | Prisma.DonorWhereInput[]
  id?: Prisma.StringFilter<"Donor"> | string
  type?: Prisma.StringFilter<"Donor"> | string
  status?: Prisma.StringFilter<"Donor"> | string
  preferredAmount?: Prisma.DecimalNullableFilter<"Donor"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.DateTimeNullableFilter<"Donor"> | Date | string | null
  fullName?: Prisma.StringNullableFilter<"Donor"> | string | null
  email?: Prisma.StringNullableFilter<"Donor"> | string | null
  phoneCode?: Prisma.StringNullableFilter<"Donor"> | string | null
  phoneNumber?: Prisma.StringNullableFilter<"Donor"> | string | null
  userProfileId?: Prisma.StringNullableFilter<"Donor"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Donor"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Donor"> | Date | string
  version?: Prisma.IntFilter<"Donor"> | number
  deletedAt?: Prisma.DateTimeNullableFilter<"Donor"> | Date | string | null
  userProfile?: Prisma.XOR<Prisma.UserProfileNullableScalarRelationFilter, Prisma.UserProfileWhereInput> | null
  donations?: Prisma.DonationListRelationFilter
}

export type DonorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  preferredAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  statusEndDate?: Prisma.SortOrderInput | Prisma.SortOrder
  fullName?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phoneCode?: Prisma.SortOrderInput | Prisma.SortOrder
  phoneNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  userProfileId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userProfile?: Prisma.UserProfileOrderByWithRelationInput
  donations?: Prisma.DonationOrderByRelationAggregateInput
}

export type DonorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  userProfileId?: string
  AND?: Prisma.DonorWhereInput | Prisma.DonorWhereInput[]
  OR?: Prisma.DonorWhereInput[]
  NOT?: Prisma.DonorWhereInput | Prisma.DonorWhereInput[]
  type?: Prisma.StringFilter<"Donor"> | string
  status?: Prisma.StringFilter<"Donor"> | string
  preferredAmount?: Prisma.DecimalNullableFilter<"Donor"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.DateTimeNullableFilter<"Donor"> | Date | string | null
  fullName?: Prisma.StringNullableFilter<"Donor"> | string | null
  phoneCode?: Prisma.StringNullableFilter<"Donor"> | string | null
  phoneNumber?: Prisma.StringNullableFilter<"Donor"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Donor"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Donor"> | Date | string
  version?: Prisma.IntFilter<"Donor"> | number
  deletedAt?: Prisma.DateTimeNullableFilter<"Donor"> | Date | string | null
  userProfile?: Prisma.XOR<Prisma.UserProfileNullableScalarRelationFilter, Prisma.UserProfileWhereInput> | null
  donations?: Prisma.DonationListRelationFilter
}, "id" | "email" | "userProfileId">

export type DonorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  preferredAmount?: Prisma.SortOrderInput | Prisma.SortOrder
  statusEndDate?: Prisma.SortOrderInput | Prisma.SortOrder
  fullName?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phoneCode?: Prisma.SortOrderInput | Prisma.SortOrder
  phoneNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  userProfileId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DonorCountOrderByAggregateInput
  _avg?: Prisma.DonorAvgOrderByAggregateInput
  _max?: Prisma.DonorMaxOrderByAggregateInput
  _min?: Prisma.DonorMinOrderByAggregateInput
  _sum?: Prisma.DonorSumOrderByAggregateInput
}

export type DonorScalarWhereWithAggregatesInput = {
  AND?: Prisma.DonorScalarWhereWithAggregatesInput | Prisma.DonorScalarWhereWithAggregatesInput[]
  OR?: Prisma.DonorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DonorScalarWhereWithAggregatesInput | Prisma.DonorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Donor"> | string
  type?: Prisma.StringWithAggregatesFilter<"Donor"> | string
  status?: Prisma.StringWithAggregatesFilter<"Donor"> | string
  preferredAmount?: Prisma.DecimalNullableWithAggregatesFilter<"Donor"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Donor"> | Date | string | null
  fullName?: Prisma.StringNullableWithAggregatesFilter<"Donor"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"Donor"> | string | null
  phoneCode?: Prisma.StringNullableWithAggregatesFilter<"Donor"> | string | null
  phoneNumber?: Prisma.StringNullableWithAggregatesFilter<"Donor"> | string | null
  userProfileId?: Prisma.StringNullableWithAggregatesFilter<"Donor"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Donor"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Donor"> | Date | string
  version?: Prisma.IntWithAggregatesFilter<"Donor"> | number
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Donor"> | Date | string | null
}

export type DonorCreateInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
  userProfile?: Prisma.UserProfileCreateNestedOneWithoutDonorInput
  donations?: Prisma.DonationCreateNestedManyWithoutDonorInput
}

export type DonorUncheckedCreateInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  userProfileId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
  donations?: Prisma.DonationUncheckedCreateNestedManyWithoutDonorInput
}

export type DonorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userProfile?: Prisma.UserProfileUpdateOneWithoutDonorNestedInput
  donations?: Prisma.DonationUpdateManyWithoutDonorNestedInput
}

export type DonorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userProfileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  donations?: Prisma.DonationUncheckedUpdateManyWithoutDonorNestedInput
}

export type DonorCreateManyInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  userProfileId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
}

export type DonorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DonorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userProfileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DonorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  preferredAmount?: Prisma.SortOrder
  statusEndDate?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneCode?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  userProfileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DonorAvgOrderByAggregateInput = {
  preferredAmount?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type DonorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  preferredAmount?: Prisma.SortOrder
  statusEndDate?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneCode?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  userProfileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DonorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  preferredAmount?: Prisma.SortOrder
  statusEndDate?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneCode?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  userProfileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DonorSumOrderByAggregateInput = {
  preferredAmount?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type DonorNullableScalarRelationFilter = {
  is?: Prisma.DonorWhereInput | null
  isNot?: Prisma.DonorWhereInput | null
}

export type DonorCreateNestedOneWithoutDonationsInput = {
  create?: Prisma.XOR<Prisma.DonorCreateWithoutDonationsInput, Prisma.DonorUncheckedCreateWithoutDonationsInput>
  connectOrCreate?: Prisma.DonorCreateOrConnectWithoutDonationsInput
  connect?: Prisma.DonorWhereUniqueInput
}

export type DonorUpdateOneWithoutDonationsNestedInput = {
  create?: Prisma.XOR<Prisma.DonorCreateWithoutDonationsInput, Prisma.DonorUncheckedCreateWithoutDonationsInput>
  connectOrCreate?: Prisma.DonorCreateOrConnectWithoutDonationsInput
  upsert?: Prisma.DonorUpsertWithoutDonationsInput
  disconnect?: Prisma.DonorWhereInput | boolean
  delete?: Prisma.DonorWhereInput | boolean
  connect?: Prisma.DonorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DonorUpdateToOneWithWhereWithoutDonationsInput, Prisma.DonorUpdateWithoutDonationsInput>, Prisma.DonorUncheckedUpdateWithoutDonationsInput>
}

export type DonorCreateNestedOneWithoutUserProfileInput = {
  create?: Prisma.XOR<Prisma.DonorCreateWithoutUserProfileInput, Prisma.DonorUncheckedCreateWithoutUserProfileInput>
  connectOrCreate?: Prisma.DonorCreateOrConnectWithoutUserProfileInput
  connect?: Prisma.DonorWhereUniqueInput
}

export type DonorUncheckedCreateNestedOneWithoutUserProfileInput = {
  create?: Prisma.XOR<Prisma.DonorCreateWithoutUserProfileInput, Prisma.DonorUncheckedCreateWithoutUserProfileInput>
  connectOrCreate?: Prisma.DonorCreateOrConnectWithoutUserProfileInput
  connect?: Prisma.DonorWhereUniqueInput
}

export type DonorUpdateOneWithoutUserProfileNestedInput = {
  create?: Prisma.XOR<Prisma.DonorCreateWithoutUserProfileInput, Prisma.DonorUncheckedCreateWithoutUserProfileInput>
  connectOrCreate?: Prisma.DonorCreateOrConnectWithoutUserProfileInput
  upsert?: Prisma.DonorUpsertWithoutUserProfileInput
  disconnect?: Prisma.DonorWhereInput | boolean
  delete?: Prisma.DonorWhereInput | boolean
  connect?: Prisma.DonorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DonorUpdateToOneWithWhereWithoutUserProfileInput, Prisma.DonorUpdateWithoutUserProfileInput>, Prisma.DonorUncheckedUpdateWithoutUserProfileInput>
}

export type DonorUncheckedUpdateOneWithoutUserProfileNestedInput = {
  create?: Prisma.XOR<Prisma.DonorCreateWithoutUserProfileInput, Prisma.DonorUncheckedCreateWithoutUserProfileInput>
  connectOrCreate?: Prisma.DonorCreateOrConnectWithoutUserProfileInput
  upsert?: Prisma.DonorUpsertWithoutUserProfileInput
  disconnect?: Prisma.DonorWhereInput | boolean
  delete?: Prisma.DonorWhereInput | boolean
  connect?: Prisma.DonorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DonorUpdateToOneWithWhereWithoutUserProfileInput, Prisma.DonorUpdateWithoutUserProfileInput>, Prisma.DonorUncheckedUpdateWithoutUserProfileInput>
}

export type DonorCreateWithoutDonationsInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
  userProfile?: Prisma.UserProfileCreateNestedOneWithoutDonorInput
}

export type DonorUncheckedCreateWithoutDonationsInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  userProfileId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
}

export type DonorCreateOrConnectWithoutDonationsInput = {
  where: Prisma.DonorWhereUniqueInput
  create: Prisma.XOR<Prisma.DonorCreateWithoutDonationsInput, Prisma.DonorUncheckedCreateWithoutDonationsInput>
}

export type DonorUpsertWithoutDonationsInput = {
  update: Prisma.XOR<Prisma.DonorUpdateWithoutDonationsInput, Prisma.DonorUncheckedUpdateWithoutDonationsInput>
  create: Prisma.XOR<Prisma.DonorCreateWithoutDonationsInput, Prisma.DonorUncheckedCreateWithoutDonationsInput>
  where?: Prisma.DonorWhereInput
}

export type DonorUpdateToOneWithWhereWithoutDonationsInput = {
  where?: Prisma.DonorWhereInput
  data: Prisma.XOR<Prisma.DonorUpdateWithoutDonationsInput, Prisma.DonorUncheckedUpdateWithoutDonationsInput>
}

export type DonorUpdateWithoutDonationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userProfile?: Prisma.UserProfileUpdateOneWithoutDonorNestedInput
}

export type DonorUncheckedUpdateWithoutDonationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userProfileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DonorCreateWithoutUserProfileInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
  donations?: Prisma.DonationCreateNestedManyWithoutDonorInput
}

export type DonorUncheckedCreateWithoutUserProfileInput = {
  id?: string
  type: string
  status: string
  preferredAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Date | string | null
  fullName?: string | null
  email?: string | null
  phoneCode?: string | null
  phoneNumber?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  deletedAt?: Date | string | null
  donations?: Prisma.DonationUncheckedCreateNestedManyWithoutDonorInput
}

export type DonorCreateOrConnectWithoutUserProfileInput = {
  where: Prisma.DonorWhereUniqueInput
  create: Prisma.XOR<Prisma.DonorCreateWithoutUserProfileInput, Prisma.DonorUncheckedCreateWithoutUserProfileInput>
}

export type DonorUpsertWithoutUserProfileInput = {
  update: Prisma.XOR<Prisma.DonorUpdateWithoutUserProfileInput, Prisma.DonorUncheckedUpdateWithoutUserProfileInput>
  create: Prisma.XOR<Prisma.DonorCreateWithoutUserProfileInput, Prisma.DonorUncheckedCreateWithoutUserProfileInput>
  where?: Prisma.DonorWhereInput
}

export type DonorUpdateToOneWithWhereWithoutUserProfileInput = {
  where?: Prisma.DonorWhereInput
  data: Prisma.XOR<Prisma.DonorUpdateWithoutUserProfileInput, Prisma.DonorUncheckedUpdateWithoutUserProfileInput>
}

export type DonorUpdateWithoutUserProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  donations?: Prisma.DonationUpdateManyWithoutDonorNestedInput
}

export type DonorUncheckedUpdateWithoutUserProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  preferredAmount?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  statusEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fullName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phoneNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  donations?: Prisma.DonationUncheckedUpdateManyWithoutDonorNestedInput
}


/**
 * Count Type DonorCountOutputType
 */

export type DonorCountOutputType = {
  donations: number
}

export type DonorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  donations?: boolean | DonorCountOutputTypeCountDonationsArgs
}

/**
 * DonorCountOutputType without action
 */
export type DonorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DonorCountOutputType
   */
  select?: Prisma.DonorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DonorCountOutputType without action
 */
export type DonorCountOutputTypeCountDonationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DonationWhereInput
}


export type DonorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  status?: boolean
  preferredAmount?: boolean
  statusEndDate?: boolean
  fullName?: boolean
  email?: boolean
  phoneCode?: boolean
  phoneNumber?: boolean
  userProfileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  deletedAt?: boolean
  userProfile?: boolean | Prisma.Donor$userProfileArgs<ExtArgs>
  donations?: boolean | Prisma.Donor$donationsArgs<ExtArgs>
  _count?: boolean | Prisma.DonorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["donor"]>

export type DonorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  status?: boolean
  preferredAmount?: boolean
  statusEndDate?: boolean
  fullName?: boolean
  email?: boolean
  phoneCode?: boolean
  phoneNumber?: boolean
  userProfileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  deletedAt?: boolean
  userProfile?: boolean | Prisma.Donor$userProfileArgs<ExtArgs>
}, ExtArgs["result"]["donor"]>

export type DonorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  status?: boolean
  preferredAmount?: boolean
  statusEndDate?: boolean
  fullName?: boolean
  email?: boolean
  phoneCode?: boolean
  phoneNumber?: boolean
  userProfileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  deletedAt?: boolean
  userProfile?: boolean | Prisma.Donor$userProfileArgs<ExtArgs>
}, ExtArgs["result"]["donor"]>

export type DonorSelectScalar = {
  id?: boolean
  type?: boolean
  status?: boolean
  preferredAmount?: boolean
  statusEndDate?: boolean
  fullName?: boolean
  email?: boolean
  phoneCode?: boolean
  phoneNumber?: boolean
  userProfileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  deletedAt?: boolean
}

export type DonorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "status" | "preferredAmount" | "statusEndDate" | "fullName" | "email" | "phoneCode" | "phoneNumber" | "userProfileId" | "createdAt" | "updatedAt" | "version" | "deletedAt", ExtArgs["result"]["donor"]>
export type DonorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userProfile?: boolean | Prisma.Donor$userProfileArgs<ExtArgs>
  donations?: boolean | Prisma.Donor$donationsArgs<ExtArgs>
  _count?: boolean | Prisma.DonorCountOutputTypeDefaultArgs<ExtArgs>
}
export type DonorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userProfile?: boolean | Prisma.Donor$userProfileArgs<ExtArgs>
}
export type DonorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userProfile?: boolean | Prisma.Donor$userProfileArgs<ExtArgs>
}

export type $DonorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Donor"
  objects: {
    userProfile: Prisma.$UserProfilePayload<ExtArgs> | null
    donations: Prisma.$DonationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: string
    status: string
    preferredAmount: runtime.Decimal | null
    statusEndDate: Date | null
    fullName: string | null
    email: string | null
    phoneCode: string | null
    phoneNumber: string | null
    userProfileId: string | null
    createdAt: Date
    updatedAt: Date
    version: number
    deletedAt: Date | null
  }, ExtArgs["result"]["donor"]>
  composites: {}
}

export type DonorGetPayload<S extends boolean | null | undefined | DonorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DonorPayload, S>

export type DonorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DonorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DonorCountAggregateInputType | true
  }

export interface DonorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Donor'], meta: { name: 'Donor' } }
  /**
   * Find zero or one Donor that matches the filter.
   * @param {DonorFindUniqueArgs} args - Arguments to find a Donor
   * @example
   * // Get one Donor
   * const donor = await prisma.donor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DonorFindUniqueArgs>(args: Prisma.SelectSubset<T, DonorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Donor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DonorFindUniqueOrThrowArgs} args - Arguments to find a Donor
   * @example
   * // Get one Donor
   * const donor = await prisma.donor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DonorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DonorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Donor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorFindFirstArgs} args - Arguments to find a Donor
   * @example
   * // Get one Donor
   * const donor = await prisma.donor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DonorFindFirstArgs>(args?: Prisma.SelectSubset<T, DonorFindFirstArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Donor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorFindFirstOrThrowArgs} args - Arguments to find a Donor
   * @example
   * // Get one Donor
   * const donor = await prisma.donor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DonorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DonorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Donors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Donors
   * const donors = await prisma.donor.findMany()
   * 
   * // Get first 10 Donors
   * const donors = await prisma.donor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const donorWithIdOnly = await prisma.donor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DonorFindManyArgs>(args?: Prisma.SelectSubset<T, DonorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Donor.
   * @param {DonorCreateArgs} args - Arguments to create a Donor.
   * @example
   * // Create one Donor
   * const Donor = await prisma.donor.create({
   *   data: {
   *     // ... data to create a Donor
   *   }
   * })
   * 
   */
  create<T extends DonorCreateArgs>(args: Prisma.SelectSubset<T, DonorCreateArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Donors.
   * @param {DonorCreateManyArgs} args - Arguments to create many Donors.
   * @example
   * // Create many Donors
   * const donor = await prisma.donor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DonorCreateManyArgs>(args?: Prisma.SelectSubset<T, DonorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Donors and returns the data saved in the database.
   * @param {DonorCreateManyAndReturnArgs} args - Arguments to create many Donors.
   * @example
   * // Create many Donors
   * const donor = await prisma.donor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Donors and only return the `id`
   * const donorWithIdOnly = await prisma.donor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DonorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DonorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Donor.
   * @param {DonorDeleteArgs} args - Arguments to delete one Donor.
   * @example
   * // Delete one Donor
   * const Donor = await prisma.donor.delete({
   *   where: {
   *     // ... filter to delete one Donor
   *   }
   * })
   * 
   */
  delete<T extends DonorDeleteArgs>(args: Prisma.SelectSubset<T, DonorDeleteArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Donor.
   * @param {DonorUpdateArgs} args - Arguments to update one Donor.
   * @example
   * // Update one Donor
   * const donor = await prisma.donor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DonorUpdateArgs>(args: Prisma.SelectSubset<T, DonorUpdateArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Donors.
   * @param {DonorDeleteManyArgs} args - Arguments to filter Donors to delete.
   * @example
   * // Delete a few Donors
   * const { count } = await prisma.donor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DonorDeleteManyArgs>(args?: Prisma.SelectSubset<T, DonorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Donors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Donors
   * const donor = await prisma.donor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DonorUpdateManyArgs>(args: Prisma.SelectSubset<T, DonorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Donors and returns the data updated in the database.
   * @param {DonorUpdateManyAndReturnArgs} args - Arguments to update many Donors.
   * @example
   * // Update many Donors
   * const donor = await prisma.donor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Donors and only return the `id`
   * const donorWithIdOnly = await prisma.donor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DonorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DonorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Donor.
   * @param {DonorUpsertArgs} args - Arguments to update or create a Donor.
   * @example
   * // Update or create a Donor
   * const donor = await prisma.donor.upsert({
   *   create: {
   *     // ... data to create a Donor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Donor we want to update
   *   }
   * })
   */
  upsert<T extends DonorUpsertArgs>(args: Prisma.SelectSubset<T, DonorUpsertArgs<ExtArgs>>): Prisma.Prisma__DonorClient<runtime.Types.Result.GetResult<Prisma.$DonorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Donors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorCountArgs} args - Arguments to filter Donors to count.
   * @example
   * // Count the number of Donors
   * const count = await prisma.donor.count({
   *   where: {
   *     // ... the filter for the Donors we want to count
   *   }
   * })
  **/
  count<T extends DonorCountArgs>(
    args?: Prisma.Subset<T, DonorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DonorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Donor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DonorAggregateArgs>(args: Prisma.Subset<T, DonorAggregateArgs>): Prisma.PrismaPromise<GetDonorAggregateType<T>>

  /**
   * Group by Donor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DonorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DonorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DonorGroupByArgs['orderBy'] }
      : { orderBy?: DonorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DonorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDonorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Donor model
 */
readonly fields: DonorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Donor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DonorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  userProfile<T extends Prisma.Donor$userProfileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Donor$userProfileArgs<ExtArgs>>): Prisma.Prisma__UserProfileClient<runtime.Types.Result.GetResult<Prisma.$UserProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  donations<T extends Prisma.Donor$donationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Donor$donationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DonationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Donor model
 */
export interface DonorFieldRefs {
  readonly id: Prisma.FieldRef<"Donor", 'String'>
  readonly type: Prisma.FieldRef<"Donor", 'String'>
  readonly status: Prisma.FieldRef<"Donor", 'String'>
  readonly preferredAmount: Prisma.FieldRef<"Donor", 'Decimal'>
  readonly statusEndDate: Prisma.FieldRef<"Donor", 'DateTime'>
  readonly fullName: Prisma.FieldRef<"Donor", 'String'>
  readonly email: Prisma.FieldRef<"Donor", 'String'>
  readonly phoneCode: Prisma.FieldRef<"Donor", 'String'>
  readonly phoneNumber: Prisma.FieldRef<"Donor", 'String'>
  readonly userProfileId: Prisma.FieldRef<"Donor", 'String'>
  readonly createdAt: Prisma.FieldRef<"Donor", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Donor", 'DateTime'>
  readonly version: Prisma.FieldRef<"Donor", 'Int'>
  readonly deletedAt: Prisma.FieldRef<"Donor", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Donor findUnique
 */
export type DonorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * Filter, which Donor to fetch.
   */
  where: Prisma.DonorWhereUniqueInput
}

/**
 * Donor findUniqueOrThrow
 */
export type DonorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * Filter, which Donor to fetch.
   */
  where: Prisma.DonorWhereUniqueInput
}

/**
 * Donor findFirst
 */
export type DonorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * Filter, which Donor to fetch.
   */
  where?: Prisma.DonorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donors to fetch.
   */
  orderBy?: Prisma.DonorOrderByWithRelationInput | Prisma.DonorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Donors.
   */
  cursor?: Prisma.DonorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Donors.
   */
  distinct?: Prisma.DonorScalarFieldEnum | Prisma.DonorScalarFieldEnum[]
}

/**
 * Donor findFirstOrThrow
 */
export type DonorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * Filter, which Donor to fetch.
   */
  where?: Prisma.DonorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donors to fetch.
   */
  orderBy?: Prisma.DonorOrderByWithRelationInput | Prisma.DonorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Donors.
   */
  cursor?: Prisma.DonorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Donors.
   */
  distinct?: Prisma.DonorScalarFieldEnum | Prisma.DonorScalarFieldEnum[]
}

/**
 * Donor findMany
 */
export type DonorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * Filter, which Donors to fetch.
   */
  where?: Prisma.DonorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Donors to fetch.
   */
  orderBy?: Prisma.DonorOrderByWithRelationInput | Prisma.DonorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Donors.
   */
  cursor?: Prisma.DonorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Donors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Donors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Donors.
   */
  distinct?: Prisma.DonorScalarFieldEnum | Prisma.DonorScalarFieldEnum[]
}

/**
 * Donor create
 */
export type DonorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * The data needed to create a Donor.
   */
  data: Prisma.XOR<Prisma.DonorCreateInput, Prisma.DonorUncheckedCreateInput>
}

/**
 * Donor createMany
 */
export type DonorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Donors.
   */
  data: Prisma.DonorCreateManyInput | Prisma.DonorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Donor createManyAndReturn
 */
export type DonorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * The data used to create many Donors.
   */
  data: Prisma.DonorCreateManyInput | Prisma.DonorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Donor update
 */
export type DonorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * The data needed to update a Donor.
   */
  data: Prisma.XOR<Prisma.DonorUpdateInput, Prisma.DonorUncheckedUpdateInput>
  /**
   * Choose, which Donor to update.
   */
  where: Prisma.DonorWhereUniqueInput
}

/**
 * Donor updateMany
 */
export type DonorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Donors.
   */
  data: Prisma.XOR<Prisma.DonorUpdateManyMutationInput, Prisma.DonorUncheckedUpdateManyInput>
  /**
   * Filter which Donors to update
   */
  where?: Prisma.DonorWhereInput
  /**
   * Limit how many Donors to update.
   */
  limit?: number
}

/**
 * Donor updateManyAndReturn
 */
export type DonorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * The data used to update Donors.
   */
  data: Prisma.XOR<Prisma.DonorUpdateManyMutationInput, Prisma.DonorUncheckedUpdateManyInput>
  /**
   * Filter which Donors to update
   */
  where?: Prisma.DonorWhereInput
  /**
   * Limit how many Donors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Donor upsert
 */
export type DonorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * The filter to search for the Donor to update in case it exists.
   */
  where: Prisma.DonorWhereUniqueInput
  /**
   * In case the Donor found by the `where` argument doesn't exist, create a new Donor with this data.
   */
  create: Prisma.XOR<Prisma.DonorCreateInput, Prisma.DonorUncheckedCreateInput>
  /**
   * In case the Donor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DonorUpdateInput, Prisma.DonorUncheckedUpdateInput>
}

/**
 * Donor delete
 */
export type DonorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
  /**
   * Filter which Donor to delete.
   */
  where: Prisma.DonorWhereUniqueInput
}

/**
 * Donor deleteMany
 */
export type DonorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Donors to delete
   */
  where?: Prisma.DonorWhereInput
  /**
   * Limit how many Donors to delete.
   */
  limit?: number
}

/**
 * Donor.userProfile
 */
export type Donor$userProfileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProfileInclude<ExtArgs> | null
  where?: Prisma.UserProfileWhereInput
}

/**
 * Donor.donations
 */
export type Donor$donationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donation
   */
  select?: Prisma.DonationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donation
   */
  omit?: Prisma.DonationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonationInclude<ExtArgs> | null
  where?: Prisma.DonationWhereInput
  orderBy?: Prisma.DonationOrderByWithRelationInput | Prisma.DonationOrderByWithRelationInput[]
  cursor?: Prisma.DonationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DonationScalarFieldEnum | Prisma.DonationScalarFieldEnum[]
}

/**
 * Donor without action
 */
export type DonorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Donor
   */
  select?: Prisma.DonorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Donor
   */
  omit?: Prisma.DonorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DonorInclude<ExtArgs> | null
}
