package ngo.nabarun.app.api.scheduler;

import java.util.Date;
import java.util.concurrent.TimeUnit;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import lombok.extern.slf4j.Slf4j;
import ngo.nabarun.app.businesslogic.IDonationBL;

@Component
@Slf4j
public class CommonJobScheduler {
	
	@Autowired
	private IDonationBL donationBL;
	
//	@Scheduled(fixedDelay = 24,timeUnit = TimeUnit.HOURS)
//	public void autoGenerateDonation() {
//		log.info("Starting Cron job AUTO_CREATE_DONATION at "+new Date());
//		donationBL.autoRaiseDonation();
//		log.info("Ending Cron job AUTO_CREATE_DONATION at "+new Date());
//	}
}
