package ngo.nabarun.domain.request.enums;


public enum RequestType {
	JOIN_REQUEST,JOIN_REQUEST_USER,CHECK_PAYMENT_GUEST, CHECK_PAYMENT, COLLECT_CASH_PAYMENT,TERMINATION_REQUEST,DONATION_PAUSE_REQUEST
	,PROFILE_UPDATE_REQUEST,
}