package ngo.nabarun.app.common.enums;

public enum RoleCode {
	MEMBER,CASHIER,ASSISTANT_CASHIER,TREASURER,GROUP_COORDINATOR,ASST_GROUP_COORDINATOR,SECRETARY,ASST_SECRETARY,COMMUNITY_MANAGER,ASST_COMMUNITY_MANAGER,PRESIDENT,VICE_PRESIDENT,TECHNICAL_SPECIALIST
}
