
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssetCustodyRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AssetCustodyRecord
 * 
 */
export type AssetCustodyRecordModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetCustodyRecordPayload>

export type AggregateAssetCustodyRecord = {
  _count: AssetCustodyRecordCountAggregateOutputType | null
  _min: AssetCustodyRecordMinAggregateOutputType | null
  _max: AssetCustodyRecordMaxAggregateOutputType | null
}

export type AssetCustodyRecordMinAggregateOutputType = {
  id: string | null
  assetId: string | null
  custodianUserId: string | null
  assignedAt: Date | null
  assignedById: string | null
  returnedAt: Date | null
  returnedById: string | null
  notes: string | null
}

export type AssetCustodyRecordMaxAggregateOutputType = {
  id: string | null
  assetId: string | null
  custodianUserId: string | null
  assignedAt: Date | null
  assignedById: string | null
  returnedAt: Date | null
  returnedById: string | null
  notes: string | null
}

export type AssetCustodyRecordCountAggregateOutputType = {
  id: number
  assetId: number
  custodianUserId: number
  assignedAt: number
  assignedById: number
  returnedAt: number
  returnedById: number
  notes: number
  _all: number
}


export type AssetCustodyRecordMinAggregateInputType = {
  id?: true
  assetId?: true
  custodianUserId?: true
  assignedAt?: true
  assignedById?: true
  returnedAt?: true
  returnedById?: true
  notes?: true
}

export type AssetCustodyRecordMaxAggregateInputType = {
  id?: true
  assetId?: true
  custodianUserId?: true
  assignedAt?: true
  assignedById?: true
  returnedAt?: true
  returnedById?: true
  notes?: true
}

export type AssetCustodyRecordCountAggregateInputType = {
  id?: true
  assetId?: true
  custodianUserId?: true
  assignedAt?: true
  assignedById?: true
  returnedAt?: true
  returnedById?: true
  notes?: true
  _all?: true
}

export type AssetCustodyRecordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetCustodyRecord to aggregate.
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetCustodyRecords to fetch.
   */
  orderBy?: Prisma.AssetCustodyRecordOrderByWithRelationInput | Prisma.AssetCustodyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetCustodyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetCustodyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetCustodyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssetCustodyRecords
  **/
  _count?: true | AssetCustodyRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetCustodyRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetCustodyRecordMaxAggregateInputType
}

export type GetAssetCustodyRecordAggregateType<T extends AssetCustodyRecordAggregateArgs> = {
      [P in keyof T & keyof AggregateAssetCustodyRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssetCustodyRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateAssetCustodyRecord[P]>
}




export type AssetCustodyRecordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetCustodyRecordWhereInput
  orderBy?: Prisma.AssetCustodyRecordOrderByWithAggregationInput | Prisma.AssetCustodyRecordOrderByWithAggregationInput[]
  by: Prisma.AssetCustodyRecordScalarFieldEnum[] | Prisma.AssetCustodyRecordScalarFieldEnum
  having?: Prisma.AssetCustodyRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetCustodyRecordCountAggregateInputType | true
  _min?: AssetCustodyRecordMinAggregateInputType
  _max?: AssetCustodyRecordMaxAggregateInputType
}

export type AssetCustodyRecordGroupByOutputType = {
  id: string
  assetId: string
  custodianUserId: string
  assignedAt: Date
  assignedById: string | null
  returnedAt: Date | null
  returnedById: string | null
  notes: string | null
  _count: AssetCustodyRecordCountAggregateOutputType | null
  _min: AssetCustodyRecordMinAggregateOutputType | null
  _max: AssetCustodyRecordMaxAggregateOutputType | null
}

export type GetAssetCustodyRecordGroupByPayload<T extends AssetCustodyRecordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetCustodyRecordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetCustodyRecordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetCustodyRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetCustodyRecordGroupByOutputType[P]>
      }
    >
  >



export type AssetCustodyRecordWhereInput = {
  AND?: Prisma.AssetCustodyRecordWhereInput | Prisma.AssetCustodyRecordWhereInput[]
  OR?: Prisma.AssetCustodyRecordWhereInput[]
  NOT?: Prisma.AssetCustodyRecordWhereInput | Prisma.AssetCustodyRecordWhereInput[]
  id?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  assetId?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  custodianUserId?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  assignedAt?: Prisma.DateTimeFilter<"AssetCustodyRecord"> | Date | string
  assignedById?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  returnedAt?: Prisma.DateTimeNullableFilter<"AssetCustodyRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  notes?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
}

export type AssetCustodyRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  custodianUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  assignedById?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedById?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  asset?: Prisma.AssetOrderByWithRelationInput
}

export type AssetCustodyRecordWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AssetCustodyRecordWhereInput | Prisma.AssetCustodyRecordWhereInput[]
  OR?: Prisma.AssetCustodyRecordWhereInput[]
  NOT?: Prisma.AssetCustodyRecordWhereInput | Prisma.AssetCustodyRecordWhereInput[]
  assetId?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  custodianUserId?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  assignedAt?: Prisma.DateTimeFilter<"AssetCustodyRecord"> | Date | string
  assignedById?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  returnedAt?: Prisma.DateTimeNullableFilter<"AssetCustodyRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  notes?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  asset?: Prisma.XOR<Prisma.AssetScalarRelationFilter, Prisma.AssetWhereInput>
}, "id">

export type AssetCustodyRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  custodianUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  assignedById?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedById?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AssetCustodyRecordCountOrderByAggregateInput
  _max?: Prisma.AssetCustodyRecordMaxOrderByAggregateInput
  _min?: Prisma.AssetCustodyRecordMinOrderByAggregateInput
}

export type AssetCustodyRecordScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetCustodyRecordScalarWhereWithAggregatesInput | Prisma.AssetCustodyRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetCustodyRecordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetCustodyRecordScalarWhereWithAggregatesInput | Prisma.AssetCustodyRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AssetCustodyRecord"> | string
  assetId?: Prisma.StringWithAggregatesFilter<"AssetCustodyRecord"> | string
  custodianUserId?: Prisma.StringWithAggregatesFilter<"AssetCustodyRecord"> | string
  assignedAt?: Prisma.DateTimeWithAggregatesFilter<"AssetCustodyRecord"> | Date | string
  assignedById?: Prisma.StringNullableWithAggregatesFilter<"AssetCustodyRecord"> | string | null
  returnedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AssetCustodyRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableWithAggregatesFilter<"AssetCustodyRecord"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"AssetCustodyRecord"> | string | null
}

export type AssetCustodyRecordCreateInput = {
  id?: string
  custodianUserId: string
  assignedAt?: Date | string
  assignedById?: string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
  asset: Prisma.AssetCreateNestedOneWithoutCustodyHistoryInput
}

export type AssetCustodyRecordUncheckedCreateInput = {
  id?: string
  assetId: string
  custodianUserId: string
  assignedAt?: Date | string
  assignedById?: string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type AssetCustodyRecordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  asset?: Prisma.AssetUpdateOneRequiredWithoutCustodyHistoryNestedInput
}

export type AssetCustodyRecordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AssetCustodyRecordCreateManyInput = {
  id?: string
  assetId: string
  custodianUserId: string
  assignedAt?: Date | string
  assignedById?: string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type AssetCustodyRecordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AssetCustodyRecordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assetId?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AssetCustodyRecordListRelationFilter = {
  every?: Prisma.AssetCustodyRecordWhereInput
  some?: Prisma.AssetCustodyRecordWhereInput
  none?: Prisma.AssetCustodyRecordWhereInput
}

export type AssetCustodyRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssetCustodyRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  custodianUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  assignedById?: Prisma.SortOrder
  returnedAt?: Prisma.SortOrder
  returnedById?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type AssetCustodyRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  custodianUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  assignedById?: Prisma.SortOrder
  returnedAt?: Prisma.SortOrder
  returnedById?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type AssetCustodyRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assetId?: Prisma.SortOrder
  custodianUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  assignedById?: Prisma.SortOrder
  returnedAt?: Prisma.SortOrder
  returnedById?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type AssetCustodyRecordCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.AssetCustodyRecordCreateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput> | Prisma.AssetCustodyRecordCreateWithoutAssetInput[] | Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput | Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.AssetCustodyRecordCreateManyAssetInputEnvelope
  connect?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
}

export type AssetCustodyRecordUncheckedCreateNestedManyWithoutAssetInput = {
  create?: Prisma.XOR<Prisma.AssetCustodyRecordCreateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput> | Prisma.AssetCustodyRecordCreateWithoutAssetInput[] | Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput | Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput[]
  createMany?: Prisma.AssetCustodyRecordCreateManyAssetInputEnvelope
  connect?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
}

export type AssetCustodyRecordUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCustodyRecordCreateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput> | Prisma.AssetCustodyRecordCreateWithoutAssetInput[] | Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput | Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.AssetCustodyRecordUpsertWithWhereUniqueWithoutAssetInput | Prisma.AssetCustodyRecordUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.AssetCustodyRecordCreateManyAssetInputEnvelope
  set?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  disconnect?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  delete?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  connect?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  update?: Prisma.AssetCustodyRecordUpdateWithWhereUniqueWithoutAssetInput | Prisma.AssetCustodyRecordUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.AssetCustodyRecordUpdateManyWithWhereWithoutAssetInput | Prisma.AssetCustodyRecordUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.AssetCustodyRecordScalarWhereInput | Prisma.AssetCustodyRecordScalarWhereInput[]
}

export type AssetCustodyRecordUncheckedUpdateManyWithoutAssetNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCustodyRecordCreateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput> | Prisma.AssetCustodyRecordCreateWithoutAssetInput[] | Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput[]
  connectOrCreate?: Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput | Prisma.AssetCustodyRecordCreateOrConnectWithoutAssetInput[]
  upsert?: Prisma.AssetCustodyRecordUpsertWithWhereUniqueWithoutAssetInput | Prisma.AssetCustodyRecordUpsertWithWhereUniqueWithoutAssetInput[]
  createMany?: Prisma.AssetCustodyRecordCreateManyAssetInputEnvelope
  set?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  disconnect?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  delete?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  connect?: Prisma.AssetCustodyRecordWhereUniqueInput | Prisma.AssetCustodyRecordWhereUniqueInput[]
  update?: Prisma.AssetCustodyRecordUpdateWithWhereUniqueWithoutAssetInput | Prisma.AssetCustodyRecordUpdateWithWhereUniqueWithoutAssetInput[]
  updateMany?: Prisma.AssetCustodyRecordUpdateManyWithWhereWithoutAssetInput | Prisma.AssetCustodyRecordUpdateManyWithWhereWithoutAssetInput[]
  deleteMany?: Prisma.AssetCustodyRecordScalarWhereInput | Prisma.AssetCustodyRecordScalarWhereInput[]
}

export type AssetCustodyRecordCreateWithoutAssetInput = {
  id?: string
  custodianUserId: string
  assignedAt?: Date | string
  assignedById?: string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type AssetCustodyRecordUncheckedCreateWithoutAssetInput = {
  id?: string
  custodianUserId: string
  assignedAt?: Date | string
  assignedById?: string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type AssetCustodyRecordCreateOrConnectWithoutAssetInput = {
  where: Prisma.AssetCustodyRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCustodyRecordCreateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput>
}

export type AssetCustodyRecordCreateManyAssetInputEnvelope = {
  data: Prisma.AssetCustodyRecordCreateManyAssetInput | Prisma.AssetCustodyRecordCreateManyAssetInput[]
  skipDuplicates?: boolean
}

export type AssetCustodyRecordUpsertWithWhereUniqueWithoutAssetInput = {
  where: Prisma.AssetCustodyRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetCustodyRecordUpdateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedUpdateWithoutAssetInput>
  create: Prisma.XOR<Prisma.AssetCustodyRecordCreateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedCreateWithoutAssetInput>
}

export type AssetCustodyRecordUpdateWithWhereUniqueWithoutAssetInput = {
  where: Prisma.AssetCustodyRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetCustodyRecordUpdateWithoutAssetInput, Prisma.AssetCustodyRecordUncheckedUpdateWithoutAssetInput>
}

export type AssetCustodyRecordUpdateManyWithWhereWithoutAssetInput = {
  where: Prisma.AssetCustodyRecordScalarWhereInput
  data: Prisma.XOR<Prisma.AssetCustodyRecordUpdateManyMutationInput, Prisma.AssetCustodyRecordUncheckedUpdateManyWithoutAssetInput>
}

export type AssetCustodyRecordScalarWhereInput = {
  AND?: Prisma.AssetCustodyRecordScalarWhereInput | Prisma.AssetCustodyRecordScalarWhereInput[]
  OR?: Prisma.AssetCustodyRecordScalarWhereInput[]
  NOT?: Prisma.AssetCustodyRecordScalarWhereInput | Prisma.AssetCustodyRecordScalarWhereInput[]
  id?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  assetId?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  custodianUserId?: Prisma.StringFilter<"AssetCustodyRecord"> | string
  assignedAt?: Prisma.DateTimeFilter<"AssetCustodyRecord"> | Date | string
  assignedById?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  returnedAt?: Prisma.DateTimeNullableFilter<"AssetCustodyRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
  notes?: Prisma.StringNullableFilter<"AssetCustodyRecord"> | string | null
}

export type AssetCustodyRecordCreateManyAssetInput = {
  id?: string
  custodianUserId: string
  assignedAt?: Date | string
  assignedById?: string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type AssetCustodyRecordUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AssetCustodyRecordUncheckedUpdateWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AssetCustodyRecordUncheckedUpdateManyWithoutAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  custodianUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AssetCustodyRecordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assetId?: boolean
  custodianUserId?: boolean
  assignedAt?: boolean
  assignedById?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetCustodyRecord"]>

export type AssetCustodyRecordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assetId?: boolean
  custodianUserId?: boolean
  assignedAt?: boolean
  assignedById?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetCustodyRecord"]>

export type AssetCustodyRecordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assetId?: boolean
  custodianUserId?: boolean
  assignedAt?: boolean
  assignedById?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assetCustodyRecord"]>

export type AssetCustodyRecordSelectScalar = {
  id?: boolean
  assetId?: boolean
  custodianUserId?: boolean
  assignedAt?: boolean
  assignedById?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
}

export type AssetCustodyRecordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "assetId" | "custodianUserId" | "assignedAt" | "assignedById" | "returnedAt" | "returnedById" | "notes", ExtArgs["result"]["assetCustodyRecord"]>
export type AssetCustodyRecordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}
export type AssetCustodyRecordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}
export type AssetCustodyRecordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  asset?: boolean | Prisma.AssetDefaultArgs<ExtArgs>
}

export type $AssetCustodyRecordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssetCustodyRecord"
  objects: {
    asset: Prisma.$AssetPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    assetId: string
    custodianUserId: string
    assignedAt: Date
    assignedById: string | null
    returnedAt: Date | null
    returnedById: string | null
    notes: string | null
  }, ExtArgs["result"]["assetCustodyRecord"]>
  composites: {}
}

export type AssetCustodyRecordGetPayload<S extends boolean | null | undefined | AssetCustodyRecordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload, S>

export type AssetCustodyRecordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetCustodyRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetCustodyRecordCountAggregateInputType | true
  }

export interface AssetCustodyRecordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssetCustodyRecord'], meta: { name: 'AssetCustodyRecord' } }
  /**
   * Find zero or one AssetCustodyRecord that matches the filter.
   * @param {AssetCustodyRecordFindUniqueArgs} args - Arguments to find a AssetCustodyRecord
   * @example
   * // Get one AssetCustodyRecord
   * const assetCustodyRecord = await prisma.assetCustodyRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetCustodyRecordFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssetCustodyRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetCustodyRecordFindUniqueOrThrowArgs} args - Arguments to find a AssetCustodyRecord
   * @example
   * // Get one AssetCustodyRecord
   * const assetCustodyRecord = await prisma.assetCustodyRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetCustodyRecordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetCustodyRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordFindFirstArgs} args - Arguments to find a AssetCustodyRecord
   * @example
   * // Get one AssetCustodyRecord
   * const assetCustodyRecord = await prisma.assetCustodyRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetCustodyRecordFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetCustodyRecordFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssetCustodyRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordFindFirstOrThrowArgs} args - Arguments to find a AssetCustodyRecord
   * @example
   * // Get one AssetCustodyRecord
   * const assetCustodyRecord = await prisma.assetCustodyRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetCustodyRecordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetCustodyRecordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssetCustodyRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssetCustodyRecords
   * const assetCustodyRecords = await prisma.assetCustodyRecord.findMany()
   * 
   * // Get first 10 AssetCustodyRecords
   * const assetCustodyRecords = await prisma.assetCustodyRecord.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assetCustodyRecordWithIdOnly = await prisma.assetCustodyRecord.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssetCustodyRecordFindManyArgs>(args?: Prisma.SelectSubset<T, AssetCustodyRecordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssetCustodyRecord.
   * @param {AssetCustodyRecordCreateArgs} args - Arguments to create a AssetCustodyRecord.
   * @example
   * // Create one AssetCustodyRecord
   * const AssetCustodyRecord = await prisma.assetCustodyRecord.create({
   *   data: {
   *     // ... data to create a AssetCustodyRecord
   *   }
   * })
   * 
   */
  create<T extends AssetCustodyRecordCreateArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordCreateArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssetCustodyRecords.
   * @param {AssetCustodyRecordCreateManyArgs} args - Arguments to create many AssetCustodyRecords.
   * @example
   * // Create many AssetCustodyRecords
   * const assetCustodyRecord = await prisma.assetCustodyRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetCustodyRecordCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetCustodyRecordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssetCustodyRecords and returns the data saved in the database.
   * @param {AssetCustodyRecordCreateManyAndReturnArgs} args - Arguments to create many AssetCustodyRecords.
   * @example
   * // Create many AssetCustodyRecords
   * const assetCustodyRecord = await prisma.assetCustodyRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssetCustodyRecords and only return the `id`
   * const assetCustodyRecordWithIdOnly = await prisma.assetCustodyRecord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetCustodyRecordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetCustodyRecordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssetCustodyRecord.
   * @param {AssetCustodyRecordDeleteArgs} args - Arguments to delete one AssetCustodyRecord.
   * @example
   * // Delete one AssetCustodyRecord
   * const AssetCustodyRecord = await prisma.assetCustodyRecord.delete({
   *   where: {
   *     // ... filter to delete one AssetCustodyRecord
   *   }
   * })
   * 
   */
  delete<T extends AssetCustodyRecordDeleteArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssetCustodyRecord.
   * @param {AssetCustodyRecordUpdateArgs} args - Arguments to update one AssetCustodyRecord.
   * @example
   * // Update one AssetCustodyRecord
   * const assetCustodyRecord = await prisma.assetCustodyRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetCustodyRecordUpdateArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssetCustodyRecords.
   * @param {AssetCustodyRecordDeleteManyArgs} args - Arguments to filter AssetCustodyRecords to delete.
   * @example
   * // Delete a few AssetCustodyRecords
   * const { count } = await prisma.assetCustodyRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetCustodyRecordDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetCustodyRecordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetCustodyRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssetCustodyRecords
   * const assetCustodyRecord = await prisma.assetCustodyRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetCustodyRecordUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssetCustodyRecords and returns the data updated in the database.
   * @param {AssetCustodyRecordUpdateManyAndReturnArgs} args - Arguments to update many AssetCustodyRecords.
   * @example
   * // Update many AssetCustodyRecords
   * const assetCustodyRecord = await prisma.assetCustodyRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssetCustodyRecords and only return the `id`
   * const assetCustodyRecordWithIdOnly = await prisma.assetCustodyRecord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetCustodyRecordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssetCustodyRecord.
   * @param {AssetCustodyRecordUpsertArgs} args - Arguments to update or create a AssetCustodyRecord.
   * @example
   * // Update or create a AssetCustodyRecord
   * const assetCustodyRecord = await prisma.assetCustodyRecord.upsert({
   *   create: {
   *     // ... data to create a AssetCustodyRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssetCustodyRecord we want to update
   *   }
   * })
   */
  upsert<T extends AssetCustodyRecordUpsertArgs>(args: Prisma.SelectSubset<T, AssetCustodyRecordUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetCustodyRecordClient<runtime.Types.Result.GetResult<Prisma.$AssetCustodyRecordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssetCustodyRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordCountArgs} args - Arguments to filter AssetCustodyRecords to count.
   * @example
   * // Count the number of AssetCustodyRecords
   * const count = await prisma.assetCustodyRecord.count({
   *   where: {
   *     // ... the filter for the AssetCustodyRecords we want to count
   *   }
   * })
  **/
  count<T extends AssetCustodyRecordCountArgs>(
    args?: Prisma.Subset<T, AssetCustodyRecordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetCustodyRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssetCustodyRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetCustodyRecordAggregateArgs>(args: Prisma.Subset<T, AssetCustodyRecordAggregateArgs>): Prisma.PrismaPromise<GetAssetCustodyRecordAggregateType<T>>

  /**
   * Group by AssetCustodyRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCustodyRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetCustodyRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetCustodyRecordGroupByArgs['orderBy'] }
      : { orderBy?: AssetCustodyRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetCustodyRecordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetCustodyRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssetCustodyRecord model
 */
readonly fields: AssetCustodyRecordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssetCustodyRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetCustodyRecordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  asset<T extends Prisma.AssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssetDefaultArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssetCustodyRecord model
 */
export interface AssetCustodyRecordFieldRefs {
  readonly id: Prisma.FieldRef<"AssetCustodyRecord", 'String'>
  readonly assetId: Prisma.FieldRef<"AssetCustodyRecord", 'String'>
  readonly custodianUserId: Prisma.FieldRef<"AssetCustodyRecord", 'String'>
  readonly assignedAt: Prisma.FieldRef<"AssetCustodyRecord", 'DateTime'>
  readonly assignedById: Prisma.FieldRef<"AssetCustodyRecord", 'String'>
  readonly returnedAt: Prisma.FieldRef<"AssetCustodyRecord", 'DateTime'>
  readonly returnedById: Prisma.FieldRef<"AssetCustodyRecord", 'String'>
  readonly notes: Prisma.FieldRef<"AssetCustodyRecord", 'String'>
}
    

// Custom InputTypes
/**
 * AssetCustodyRecord findUnique
 */
export type AssetCustodyRecordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * Filter, which AssetCustodyRecord to fetch.
   */
  where: Prisma.AssetCustodyRecordWhereUniqueInput
}

/**
 * AssetCustodyRecord findUniqueOrThrow
 */
export type AssetCustodyRecordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * Filter, which AssetCustodyRecord to fetch.
   */
  where: Prisma.AssetCustodyRecordWhereUniqueInput
}

/**
 * AssetCustodyRecord findFirst
 */
export type AssetCustodyRecordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * Filter, which AssetCustodyRecord to fetch.
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetCustodyRecords to fetch.
   */
  orderBy?: Prisma.AssetCustodyRecordOrderByWithRelationInput | Prisma.AssetCustodyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetCustodyRecords.
   */
  cursor?: Prisma.AssetCustodyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetCustodyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetCustodyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetCustodyRecords.
   */
  distinct?: Prisma.AssetCustodyRecordScalarFieldEnum | Prisma.AssetCustodyRecordScalarFieldEnum[]
}

/**
 * AssetCustodyRecord findFirstOrThrow
 */
export type AssetCustodyRecordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * Filter, which AssetCustodyRecord to fetch.
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetCustodyRecords to fetch.
   */
  orderBy?: Prisma.AssetCustodyRecordOrderByWithRelationInput | Prisma.AssetCustodyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssetCustodyRecords.
   */
  cursor?: Prisma.AssetCustodyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetCustodyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetCustodyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetCustodyRecords.
   */
  distinct?: Prisma.AssetCustodyRecordScalarFieldEnum | Prisma.AssetCustodyRecordScalarFieldEnum[]
}

/**
 * AssetCustodyRecord findMany
 */
export type AssetCustodyRecordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * Filter, which AssetCustodyRecords to fetch.
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssetCustodyRecords to fetch.
   */
  orderBy?: Prisma.AssetCustodyRecordOrderByWithRelationInput | Prisma.AssetCustodyRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssetCustodyRecords.
   */
  cursor?: Prisma.AssetCustodyRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssetCustodyRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssetCustodyRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssetCustodyRecords.
   */
  distinct?: Prisma.AssetCustodyRecordScalarFieldEnum | Prisma.AssetCustodyRecordScalarFieldEnum[]
}

/**
 * AssetCustodyRecord create
 */
export type AssetCustodyRecordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a AssetCustodyRecord.
   */
  data: Prisma.XOR<Prisma.AssetCustodyRecordCreateInput, Prisma.AssetCustodyRecordUncheckedCreateInput>
}

/**
 * AssetCustodyRecord createMany
 */
export type AssetCustodyRecordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssetCustodyRecords.
   */
  data: Prisma.AssetCustodyRecordCreateManyInput | Prisma.AssetCustodyRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssetCustodyRecord createManyAndReturn
 */
export type AssetCustodyRecordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * The data used to create many AssetCustodyRecords.
   */
  data: Prisma.AssetCustodyRecordCreateManyInput | Prisma.AssetCustodyRecordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssetCustodyRecord update
 */
export type AssetCustodyRecordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a AssetCustodyRecord.
   */
  data: Prisma.XOR<Prisma.AssetCustodyRecordUpdateInput, Prisma.AssetCustodyRecordUncheckedUpdateInput>
  /**
   * Choose, which AssetCustodyRecord to update.
   */
  where: Prisma.AssetCustodyRecordWhereUniqueInput
}

/**
 * AssetCustodyRecord updateMany
 */
export type AssetCustodyRecordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssetCustodyRecords.
   */
  data: Prisma.XOR<Prisma.AssetCustodyRecordUpdateManyMutationInput, Prisma.AssetCustodyRecordUncheckedUpdateManyInput>
  /**
   * Filter which AssetCustodyRecords to update
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * Limit how many AssetCustodyRecords to update.
   */
  limit?: number
}

/**
 * AssetCustodyRecord updateManyAndReturn
 */
export type AssetCustodyRecordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * The data used to update AssetCustodyRecords.
   */
  data: Prisma.XOR<Prisma.AssetCustodyRecordUpdateManyMutationInput, Prisma.AssetCustodyRecordUncheckedUpdateManyInput>
  /**
   * Filter which AssetCustodyRecords to update
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * Limit how many AssetCustodyRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssetCustodyRecord upsert
 */
export type AssetCustodyRecordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the AssetCustodyRecord to update in case it exists.
   */
  where: Prisma.AssetCustodyRecordWhereUniqueInput
  /**
   * In case the AssetCustodyRecord found by the `where` argument doesn't exist, create a new AssetCustodyRecord with this data.
   */
  create: Prisma.XOR<Prisma.AssetCustodyRecordCreateInput, Prisma.AssetCustodyRecordUncheckedCreateInput>
  /**
   * In case the AssetCustodyRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetCustodyRecordUpdateInput, Prisma.AssetCustodyRecordUncheckedUpdateInput>
}

/**
 * AssetCustodyRecord delete
 */
export type AssetCustodyRecordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
  /**
   * Filter which AssetCustodyRecord to delete.
   */
  where: Prisma.AssetCustodyRecordWhereUniqueInput
}

/**
 * AssetCustodyRecord deleteMany
 */
export type AssetCustodyRecordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssetCustodyRecords to delete
   */
  where?: Prisma.AssetCustodyRecordWhereInput
  /**
   * Limit how many AssetCustodyRecords to delete.
   */
  limit?: number
}

/**
 * AssetCustodyRecord without action
 */
export type AssetCustodyRecordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssetCustodyRecord
   */
  select?: Prisma.AssetCustodyRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssetCustodyRecord
   */
  omit?: Prisma.AssetCustodyRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetCustodyRecordInclude<ExtArgs> | null
}
