
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BookLoanRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BookLoanRecord
 * 
 */
export type BookLoanRecordModel = runtime.Types.Result.DefaultSelection<Prisma.$BookLoanRecordPayload>

export type AggregateBookLoanRecord = {
  _count: BookLoanRecordCountAggregateOutputType | null
  _min: BookLoanRecordMinAggregateOutputType | null
  _max: BookLoanRecordMaxAggregateOutputType | null
}

export type BookLoanRecordMinAggregateOutputType = {
  id: string | null
  bookId: string | null
  borrowerUserId: string | null
  guestName: string | null
  loanedAt: Date | null
  dueDate: Date | null
  returnedAt: Date | null
  returnedById: string | null
  notes: string | null
}

export type BookLoanRecordMaxAggregateOutputType = {
  id: string | null
  bookId: string | null
  borrowerUserId: string | null
  guestName: string | null
  loanedAt: Date | null
  dueDate: Date | null
  returnedAt: Date | null
  returnedById: string | null
  notes: string | null
}

export type BookLoanRecordCountAggregateOutputType = {
  id: number
  bookId: number
  borrowerUserId: number
  guestName: number
  loanedAt: number
  dueDate: number
  returnedAt: number
  returnedById: number
  notes: number
  _all: number
}


export type BookLoanRecordMinAggregateInputType = {
  id?: true
  bookId?: true
  borrowerUserId?: true
  guestName?: true
  loanedAt?: true
  dueDate?: true
  returnedAt?: true
  returnedById?: true
  notes?: true
}

export type BookLoanRecordMaxAggregateInputType = {
  id?: true
  bookId?: true
  borrowerUserId?: true
  guestName?: true
  loanedAt?: true
  dueDate?: true
  returnedAt?: true
  returnedById?: true
  notes?: true
}

export type BookLoanRecordCountAggregateInputType = {
  id?: true
  bookId?: true
  borrowerUserId?: true
  guestName?: true
  loanedAt?: true
  dueDate?: true
  returnedAt?: true
  returnedById?: true
  notes?: true
  _all?: true
}

export type BookLoanRecordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BookLoanRecord to aggregate.
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookLoanRecords to fetch.
   */
  orderBy?: Prisma.BookLoanRecordOrderByWithRelationInput | Prisma.BookLoanRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BookLoanRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookLoanRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookLoanRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BookLoanRecords
  **/
  _count?: true | BookLoanRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BookLoanRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BookLoanRecordMaxAggregateInputType
}

export type GetBookLoanRecordAggregateType<T extends BookLoanRecordAggregateArgs> = {
      [P in keyof T & keyof AggregateBookLoanRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBookLoanRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateBookLoanRecord[P]>
}




export type BookLoanRecordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookLoanRecordWhereInput
  orderBy?: Prisma.BookLoanRecordOrderByWithAggregationInput | Prisma.BookLoanRecordOrderByWithAggregationInput[]
  by: Prisma.BookLoanRecordScalarFieldEnum[] | Prisma.BookLoanRecordScalarFieldEnum
  having?: Prisma.BookLoanRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BookLoanRecordCountAggregateInputType | true
  _min?: BookLoanRecordMinAggregateInputType
  _max?: BookLoanRecordMaxAggregateInputType
}

export type BookLoanRecordGroupByOutputType = {
  id: string
  bookId: string
  borrowerUserId: string | null
  guestName: string | null
  loanedAt: Date
  dueDate: Date | null
  returnedAt: Date | null
  returnedById: string | null
  notes: string | null
  _count: BookLoanRecordCountAggregateOutputType | null
  _min: BookLoanRecordMinAggregateOutputType | null
  _max: BookLoanRecordMaxAggregateOutputType | null
}

export type GetBookLoanRecordGroupByPayload<T extends BookLoanRecordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BookLoanRecordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BookLoanRecordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BookLoanRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BookLoanRecordGroupByOutputType[P]>
      }
    >
  >



export type BookLoanRecordWhereInput = {
  AND?: Prisma.BookLoanRecordWhereInput | Prisma.BookLoanRecordWhereInput[]
  OR?: Prisma.BookLoanRecordWhereInput[]
  NOT?: Prisma.BookLoanRecordWhereInput | Prisma.BookLoanRecordWhereInput[]
  id?: Prisma.StringFilter<"BookLoanRecord"> | string
  bookId?: Prisma.StringFilter<"BookLoanRecord"> | string
  borrowerUserId?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  guestName?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  loanedAt?: Prisma.DateTimeFilter<"BookLoanRecord"> | Date | string
  dueDate?: Prisma.DateTimeNullableFilter<"BookLoanRecord"> | Date | string | null
  returnedAt?: Prisma.DateTimeNullableFilter<"BookLoanRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  notes?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  book?: Prisma.XOR<Prisma.BookScalarRelationFilter, Prisma.BookWhereInput>
}

export type BookLoanRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  borrowerUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  guestName?: Prisma.SortOrderInput | Prisma.SortOrder
  loanedAt?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedById?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  book?: Prisma.BookOrderByWithRelationInput
}

export type BookLoanRecordWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BookLoanRecordWhereInput | Prisma.BookLoanRecordWhereInput[]
  OR?: Prisma.BookLoanRecordWhereInput[]
  NOT?: Prisma.BookLoanRecordWhereInput | Prisma.BookLoanRecordWhereInput[]
  bookId?: Prisma.StringFilter<"BookLoanRecord"> | string
  borrowerUserId?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  guestName?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  loanedAt?: Prisma.DateTimeFilter<"BookLoanRecord"> | Date | string
  dueDate?: Prisma.DateTimeNullableFilter<"BookLoanRecord"> | Date | string | null
  returnedAt?: Prisma.DateTimeNullableFilter<"BookLoanRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  notes?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  book?: Prisma.XOR<Prisma.BookScalarRelationFilter, Prisma.BookWhereInput>
}, "id">

export type BookLoanRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  borrowerUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  guestName?: Prisma.SortOrderInput | Prisma.SortOrder
  loanedAt?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  returnedById?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BookLoanRecordCountOrderByAggregateInput
  _max?: Prisma.BookLoanRecordMaxOrderByAggregateInput
  _min?: Prisma.BookLoanRecordMinOrderByAggregateInput
}

export type BookLoanRecordScalarWhereWithAggregatesInput = {
  AND?: Prisma.BookLoanRecordScalarWhereWithAggregatesInput | Prisma.BookLoanRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.BookLoanRecordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BookLoanRecordScalarWhereWithAggregatesInput | Prisma.BookLoanRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BookLoanRecord"> | string
  bookId?: Prisma.StringWithAggregatesFilter<"BookLoanRecord"> | string
  borrowerUserId?: Prisma.StringNullableWithAggregatesFilter<"BookLoanRecord"> | string | null
  guestName?: Prisma.StringNullableWithAggregatesFilter<"BookLoanRecord"> | string | null
  loanedAt?: Prisma.DateTimeWithAggregatesFilter<"BookLoanRecord"> | Date | string
  dueDate?: Prisma.DateTimeNullableWithAggregatesFilter<"BookLoanRecord"> | Date | string | null
  returnedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"BookLoanRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableWithAggregatesFilter<"BookLoanRecord"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"BookLoanRecord"> | string | null
}

export type BookLoanRecordCreateInput = {
  id?: string
  borrowerUserId?: string | null
  guestName?: string | null
  loanedAt?: Date | string
  dueDate?: Date | string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
  book: Prisma.BookCreateNestedOneWithoutLoanHistoryInput
}

export type BookLoanRecordUncheckedCreateInput = {
  id?: string
  bookId: string
  borrowerUserId?: string | null
  guestName?: string | null
  loanedAt?: Date | string
  dueDate?: Date | string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type BookLoanRecordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  book?: Prisma.BookUpdateOneRequiredWithoutLoanHistoryNestedInput
}

export type BookLoanRecordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BookLoanRecordCreateManyInput = {
  id?: string
  bookId: string
  borrowerUserId?: string | null
  guestName?: string | null
  loanedAt?: Date | string
  dueDate?: Date | string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type BookLoanRecordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BookLoanRecordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookId?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BookLoanRecordListRelationFilter = {
  every?: Prisma.BookLoanRecordWhereInput
  some?: Prisma.BookLoanRecordWhereInput
  none?: Prisma.BookLoanRecordWhereInput
}

export type BookLoanRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BookLoanRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  borrowerUserId?: Prisma.SortOrder
  guestName?: Prisma.SortOrder
  loanedAt?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  returnedAt?: Prisma.SortOrder
  returnedById?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type BookLoanRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  borrowerUserId?: Prisma.SortOrder
  guestName?: Prisma.SortOrder
  loanedAt?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  returnedAt?: Prisma.SortOrder
  returnedById?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type BookLoanRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  borrowerUserId?: Prisma.SortOrder
  guestName?: Prisma.SortOrder
  loanedAt?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  returnedAt?: Prisma.SortOrder
  returnedById?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type BookLoanRecordCreateNestedManyWithoutBookInput = {
  create?: Prisma.XOR<Prisma.BookLoanRecordCreateWithoutBookInput, Prisma.BookLoanRecordUncheckedCreateWithoutBookInput> | Prisma.BookLoanRecordCreateWithoutBookInput[] | Prisma.BookLoanRecordUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.BookLoanRecordCreateOrConnectWithoutBookInput | Prisma.BookLoanRecordCreateOrConnectWithoutBookInput[]
  createMany?: Prisma.BookLoanRecordCreateManyBookInputEnvelope
  connect?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
}

export type BookLoanRecordUncheckedCreateNestedManyWithoutBookInput = {
  create?: Prisma.XOR<Prisma.BookLoanRecordCreateWithoutBookInput, Prisma.BookLoanRecordUncheckedCreateWithoutBookInput> | Prisma.BookLoanRecordCreateWithoutBookInput[] | Prisma.BookLoanRecordUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.BookLoanRecordCreateOrConnectWithoutBookInput | Prisma.BookLoanRecordCreateOrConnectWithoutBookInput[]
  createMany?: Prisma.BookLoanRecordCreateManyBookInputEnvelope
  connect?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
}

export type BookLoanRecordUpdateManyWithoutBookNestedInput = {
  create?: Prisma.XOR<Prisma.BookLoanRecordCreateWithoutBookInput, Prisma.BookLoanRecordUncheckedCreateWithoutBookInput> | Prisma.BookLoanRecordCreateWithoutBookInput[] | Prisma.BookLoanRecordUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.BookLoanRecordCreateOrConnectWithoutBookInput | Prisma.BookLoanRecordCreateOrConnectWithoutBookInput[]
  upsert?: Prisma.BookLoanRecordUpsertWithWhereUniqueWithoutBookInput | Prisma.BookLoanRecordUpsertWithWhereUniqueWithoutBookInput[]
  createMany?: Prisma.BookLoanRecordCreateManyBookInputEnvelope
  set?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  disconnect?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  delete?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  connect?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  update?: Prisma.BookLoanRecordUpdateWithWhereUniqueWithoutBookInput | Prisma.BookLoanRecordUpdateWithWhereUniqueWithoutBookInput[]
  updateMany?: Prisma.BookLoanRecordUpdateManyWithWhereWithoutBookInput | Prisma.BookLoanRecordUpdateManyWithWhereWithoutBookInput[]
  deleteMany?: Prisma.BookLoanRecordScalarWhereInput | Prisma.BookLoanRecordScalarWhereInput[]
}

export type BookLoanRecordUncheckedUpdateManyWithoutBookNestedInput = {
  create?: Prisma.XOR<Prisma.BookLoanRecordCreateWithoutBookInput, Prisma.BookLoanRecordUncheckedCreateWithoutBookInput> | Prisma.BookLoanRecordCreateWithoutBookInput[] | Prisma.BookLoanRecordUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.BookLoanRecordCreateOrConnectWithoutBookInput | Prisma.BookLoanRecordCreateOrConnectWithoutBookInput[]
  upsert?: Prisma.BookLoanRecordUpsertWithWhereUniqueWithoutBookInput | Prisma.BookLoanRecordUpsertWithWhereUniqueWithoutBookInput[]
  createMany?: Prisma.BookLoanRecordCreateManyBookInputEnvelope
  set?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  disconnect?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  delete?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  connect?: Prisma.BookLoanRecordWhereUniqueInput | Prisma.BookLoanRecordWhereUniqueInput[]
  update?: Prisma.BookLoanRecordUpdateWithWhereUniqueWithoutBookInput | Prisma.BookLoanRecordUpdateWithWhereUniqueWithoutBookInput[]
  updateMany?: Prisma.BookLoanRecordUpdateManyWithWhereWithoutBookInput | Prisma.BookLoanRecordUpdateManyWithWhereWithoutBookInput[]
  deleteMany?: Prisma.BookLoanRecordScalarWhereInput | Prisma.BookLoanRecordScalarWhereInput[]
}

export type BookLoanRecordCreateWithoutBookInput = {
  id?: string
  borrowerUserId?: string | null
  guestName?: string | null
  loanedAt?: Date | string
  dueDate?: Date | string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type BookLoanRecordUncheckedCreateWithoutBookInput = {
  id?: string
  borrowerUserId?: string | null
  guestName?: string | null
  loanedAt?: Date | string
  dueDate?: Date | string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type BookLoanRecordCreateOrConnectWithoutBookInput = {
  where: Prisma.BookLoanRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.BookLoanRecordCreateWithoutBookInput, Prisma.BookLoanRecordUncheckedCreateWithoutBookInput>
}

export type BookLoanRecordCreateManyBookInputEnvelope = {
  data: Prisma.BookLoanRecordCreateManyBookInput | Prisma.BookLoanRecordCreateManyBookInput[]
  skipDuplicates?: boolean
}

export type BookLoanRecordUpsertWithWhereUniqueWithoutBookInput = {
  where: Prisma.BookLoanRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.BookLoanRecordUpdateWithoutBookInput, Prisma.BookLoanRecordUncheckedUpdateWithoutBookInput>
  create: Prisma.XOR<Prisma.BookLoanRecordCreateWithoutBookInput, Prisma.BookLoanRecordUncheckedCreateWithoutBookInput>
}

export type BookLoanRecordUpdateWithWhereUniqueWithoutBookInput = {
  where: Prisma.BookLoanRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.BookLoanRecordUpdateWithoutBookInput, Prisma.BookLoanRecordUncheckedUpdateWithoutBookInput>
}

export type BookLoanRecordUpdateManyWithWhereWithoutBookInput = {
  where: Prisma.BookLoanRecordScalarWhereInput
  data: Prisma.XOR<Prisma.BookLoanRecordUpdateManyMutationInput, Prisma.BookLoanRecordUncheckedUpdateManyWithoutBookInput>
}

export type BookLoanRecordScalarWhereInput = {
  AND?: Prisma.BookLoanRecordScalarWhereInput | Prisma.BookLoanRecordScalarWhereInput[]
  OR?: Prisma.BookLoanRecordScalarWhereInput[]
  NOT?: Prisma.BookLoanRecordScalarWhereInput | Prisma.BookLoanRecordScalarWhereInput[]
  id?: Prisma.StringFilter<"BookLoanRecord"> | string
  bookId?: Prisma.StringFilter<"BookLoanRecord"> | string
  borrowerUserId?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  guestName?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  loanedAt?: Prisma.DateTimeFilter<"BookLoanRecord"> | Date | string
  dueDate?: Prisma.DateTimeNullableFilter<"BookLoanRecord"> | Date | string | null
  returnedAt?: Prisma.DateTimeNullableFilter<"BookLoanRecord"> | Date | string | null
  returnedById?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
  notes?: Prisma.StringNullableFilter<"BookLoanRecord"> | string | null
}

export type BookLoanRecordCreateManyBookInput = {
  id?: string
  borrowerUserId?: string | null
  guestName?: string | null
  loanedAt?: Date | string
  dueDate?: Date | string | null
  returnedAt?: Date | string | null
  returnedById?: string | null
  notes?: string | null
}

export type BookLoanRecordUpdateWithoutBookInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BookLoanRecordUncheckedUpdateWithoutBookInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BookLoanRecordUncheckedUpdateManyWithoutBookInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  borrowerUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  loanedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  returnedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type BookLoanRecordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookId?: boolean
  borrowerUserId?: boolean
  guestName?: boolean
  loanedAt?: boolean
  dueDate?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
  book?: boolean | Prisma.BookDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bookLoanRecord"]>

export type BookLoanRecordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookId?: boolean
  borrowerUserId?: boolean
  guestName?: boolean
  loanedAt?: boolean
  dueDate?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
  book?: boolean | Prisma.BookDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bookLoanRecord"]>

export type BookLoanRecordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookId?: boolean
  borrowerUserId?: boolean
  guestName?: boolean
  loanedAt?: boolean
  dueDate?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
  book?: boolean | Prisma.BookDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bookLoanRecord"]>

export type BookLoanRecordSelectScalar = {
  id?: boolean
  bookId?: boolean
  borrowerUserId?: boolean
  guestName?: boolean
  loanedAt?: boolean
  dueDate?: boolean
  returnedAt?: boolean
  returnedById?: boolean
  notes?: boolean
}

export type BookLoanRecordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bookId" | "borrowerUserId" | "guestName" | "loanedAt" | "dueDate" | "returnedAt" | "returnedById" | "notes", ExtArgs["result"]["bookLoanRecord"]>
export type BookLoanRecordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  book?: boolean | Prisma.BookDefaultArgs<ExtArgs>
}
export type BookLoanRecordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  book?: boolean | Prisma.BookDefaultArgs<ExtArgs>
}
export type BookLoanRecordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  book?: boolean | Prisma.BookDefaultArgs<ExtArgs>
}

export type $BookLoanRecordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BookLoanRecord"
  objects: {
    book: Prisma.$BookPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    bookId: string
    borrowerUserId: string | null
    guestName: string | null
    loanedAt: Date
    dueDate: Date | null
    returnedAt: Date | null
    returnedById: string | null
    notes: string | null
  }, ExtArgs["result"]["bookLoanRecord"]>
  composites: {}
}

export type BookLoanRecordGetPayload<S extends boolean | null | undefined | BookLoanRecordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload, S>

export type BookLoanRecordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BookLoanRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BookLoanRecordCountAggregateInputType | true
  }

export interface BookLoanRecordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BookLoanRecord'], meta: { name: 'BookLoanRecord' } }
  /**
   * Find zero or one BookLoanRecord that matches the filter.
   * @param {BookLoanRecordFindUniqueArgs} args - Arguments to find a BookLoanRecord
   * @example
   * // Get one BookLoanRecord
   * const bookLoanRecord = await prisma.bookLoanRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BookLoanRecordFindUniqueArgs>(args: Prisma.SelectSubset<T, BookLoanRecordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BookLoanRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BookLoanRecordFindUniqueOrThrowArgs} args - Arguments to find a BookLoanRecord
   * @example
   * // Get one BookLoanRecord
   * const bookLoanRecord = await prisma.bookLoanRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BookLoanRecordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BookLoanRecordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BookLoanRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordFindFirstArgs} args - Arguments to find a BookLoanRecord
   * @example
   * // Get one BookLoanRecord
   * const bookLoanRecord = await prisma.bookLoanRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BookLoanRecordFindFirstArgs>(args?: Prisma.SelectSubset<T, BookLoanRecordFindFirstArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BookLoanRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordFindFirstOrThrowArgs} args - Arguments to find a BookLoanRecord
   * @example
   * // Get one BookLoanRecord
   * const bookLoanRecord = await prisma.bookLoanRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BookLoanRecordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BookLoanRecordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BookLoanRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BookLoanRecords
   * const bookLoanRecords = await prisma.bookLoanRecord.findMany()
   * 
   * // Get first 10 BookLoanRecords
   * const bookLoanRecords = await prisma.bookLoanRecord.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bookLoanRecordWithIdOnly = await prisma.bookLoanRecord.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BookLoanRecordFindManyArgs>(args?: Prisma.SelectSubset<T, BookLoanRecordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BookLoanRecord.
   * @param {BookLoanRecordCreateArgs} args - Arguments to create a BookLoanRecord.
   * @example
   * // Create one BookLoanRecord
   * const BookLoanRecord = await prisma.bookLoanRecord.create({
   *   data: {
   *     // ... data to create a BookLoanRecord
   *   }
   * })
   * 
   */
  create<T extends BookLoanRecordCreateArgs>(args: Prisma.SelectSubset<T, BookLoanRecordCreateArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BookLoanRecords.
   * @param {BookLoanRecordCreateManyArgs} args - Arguments to create many BookLoanRecords.
   * @example
   * // Create many BookLoanRecords
   * const bookLoanRecord = await prisma.bookLoanRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BookLoanRecordCreateManyArgs>(args?: Prisma.SelectSubset<T, BookLoanRecordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BookLoanRecords and returns the data saved in the database.
   * @param {BookLoanRecordCreateManyAndReturnArgs} args - Arguments to create many BookLoanRecords.
   * @example
   * // Create many BookLoanRecords
   * const bookLoanRecord = await prisma.bookLoanRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BookLoanRecords and only return the `id`
   * const bookLoanRecordWithIdOnly = await prisma.bookLoanRecord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BookLoanRecordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BookLoanRecordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BookLoanRecord.
   * @param {BookLoanRecordDeleteArgs} args - Arguments to delete one BookLoanRecord.
   * @example
   * // Delete one BookLoanRecord
   * const BookLoanRecord = await prisma.bookLoanRecord.delete({
   *   where: {
   *     // ... filter to delete one BookLoanRecord
   *   }
   * })
   * 
   */
  delete<T extends BookLoanRecordDeleteArgs>(args: Prisma.SelectSubset<T, BookLoanRecordDeleteArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BookLoanRecord.
   * @param {BookLoanRecordUpdateArgs} args - Arguments to update one BookLoanRecord.
   * @example
   * // Update one BookLoanRecord
   * const bookLoanRecord = await prisma.bookLoanRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BookLoanRecordUpdateArgs>(args: Prisma.SelectSubset<T, BookLoanRecordUpdateArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BookLoanRecords.
   * @param {BookLoanRecordDeleteManyArgs} args - Arguments to filter BookLoanRecords to delete.
   * @example
   * // Delete a few BookLoanRecords
   * const { count } = await prisma.bookLoanRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BookLoanRecordDeleteManyArgs>(args?: Prisma.SelectSubset<T, BookLoanRecordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BookLoanRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BookLoanRecords
   * const bookLoanRecord = await prisma.bookLoanRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BookLoanRecordUpdateManyArgs>(args: Prisma.SelectSubset<T, BookLoanRecordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BookLoanRecords and returns the data updated in the database.
   * @param {BookLoanRecordUpdateManyAndReturnArgs} args - Arguments to update many BookLoanRecords.
   * @example
   * // Update many BookLoanRecords
   * const bookLoanRecord = await prisma.bookLoanRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BookLoanRecords and only return the `id`
   * const bookLoanRecordWithIdOnly = await prisma.bookLoanRecord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BookLoanRecordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BookLoanRecordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BookLoanRecord.
   * @param {BookLoanRecordUpsertArgs} args - Arguments to update or create a BookLoanRecord.
   * @example
   * // Update or create a BookLoanRecord
   * const bookLoanRecord = await prisma.bookLoanRecord.upsert({
   *   create: {
   *     // ... data to create a BookLoanRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BookLoanRecord we want to update
   *   }
   * })
   */
  upsert<T extends BookLoanRecordUpsertArgs>(args: Prisma.SelectSubset<T, BookLoanRecordUpsertArgs<ExtArgs>>): Prisma.Prisma__BookLoanRecordClient<runtime.Types.Result.GetResult<Prisma.$BookLoanRecordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BookLoanRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordCountArgs} args - Arguments to filter BookLoanRecords to count.
   * @example
   * // Count the number of BookLoanRecords
   * const count = await prisma.bookLoanRecord.count({
   *   where: {
   *     // ... the filter for the BookLoanRecords we want to count
   *   }
   * })
  **/
  count<T extends BookLoanRecordCountArgs>(
    args?: Prisma.Subset<T, BookLoanRecordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BookLoanRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BookLoanRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BookLoanRecordAggregateArgs>(args: Prisma.Subset<T, BookLoanRecordAggregateArgs>): Prisma.PrismaPromise<GetBookLoanRecordAggregateType<T>>

  /**
   * Group by BookLoanRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookLoanRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BookLoanRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BookLoanRecordGroupByArgs['orderBy'] }
      : { orderBy?: BookLoanRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BookLoanRecordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBookLoanRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BookLoanRecord model
 */
readonly fields: BookLoanRecordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BookLoanRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BookLoanRecordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  book<T extends Prisma.BookDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BookDefaultArgs<ExtArgs>>): Prisma.Prisma__BookClient<runtime.Types.Result.GetResult<Prisma.$BookPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BookLoanRecord model
 */
export interface BookLoanRecordFieldRefs {
  readonly id: Prisma.FieldRef<"BookLoanRecord", 'String'>
  readonly bookId: Prisma.FieldRef<"BookLoanRecord", 'String'>
  readonly borrowerUserId: Prisma.FieldRef<"BookLoanRecord", 'String'>
  readonly guestName: Prisma.FieldRef<"BookLoanRecord", 'String'>
  readonly loanedAt: Prisma.FieldRef<"BookLoanRecord", 'DateTime'>
  readonly dueDate: Prisma.FieldRef<"BookLoanRecord", 'DateTime'>
  readonly returnedAt: Prisma.FieldRef<"BookLoanRecord", 'DateTime'>
  readonly returnedById: Prisma.FieldRef<"BookLoanRecord", 'String'>
  readonly notes: Prisma.FieldRef<"BookLoanRecord", 'String'>
}
    

// Custom InputTypes
/**
 * BookLoanRecord findUnique
 */
export type BookLoanRecordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * Filter, which BookLoanRecord to fetch.
   */
  where: Prisma.BookLoanRecordWhereUniqueInput
}

/**
 * BookLoanRecord findUniqueOrThrow
 */
export type BookLoanRecordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * Filter, which BookLoanRecord to fetch.
   */
  where: Prisma.BookLoanRecordWhereUniqueInput
}

/**
 * BookLoanRecord findFirst
 */
export type BookLoanRecordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * Filter, which BookLoanRecord to fetch.
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookLoanRecords to fetch.
   */
  orderBy?: Prisma.BookLoanRecordOrderByWithRelationInput | Prisma.BookLoanRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BookLoanRecords.
   */
  cursor?: Prisma.BookLoanRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookLoanRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookLoanRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BookLoanRecords.
   */
  distinct?: Prisma.BookLoanRecordScalarFieldEnum | Prisma.BookLoanRecordScalarFieldEnum[]
}

/**
 * BookLoanRecord findFirstOrThrow
 */
export type BookLoanRecordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * Filter, which BookLoanRecord to fetch.
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookLoanRecords to fetch.
   */
  orderBy?: Prisma.BookLoanRecordOrderByWithRelationInput | Prisma.BookLoanRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BookLoanRecords.
   */
  cursor?: Prisma.BookLoanRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookLoanRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookLoanRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BookLoanRecords.
   */
  distinct?: Prisma.BookLoanRecordScalarFieldEnum | Prisma.BookLoanRecordScalarFieldEnum[]
}

/**
 * BookLoanRecord findMany
 */
export type BookLoanRecordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * Filter, which BookLoanRecords to fetch.
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookLoanRecords to fetch.
   */
  orderBy?: Prisma.BookLoanRecordOrderByWithRelationInput | Prisma.BookLoanRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BookLoanRecords.
   */
  cursor?: Prisma.BookLoanRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookLoanRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookLoanRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BookLoanRecords.
   */
  distinct?: Prisma.BookLoanRecordScalarFieldEnum | Prisma.BookLoanRecordScalarFieldEnum[]
}

/**
 * BookLoanRecord create
 */
export type BookLoanRecordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a BookLoanRecord.
   */
  data: Prisma.XOR<Prisma.BookLoanRecordCreateInput, Prisma.BookLoanRecordUncheckedCreateInput>
}

/**
 * BookLoanRecord createMany
 */
export type BookLoanRecordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BookLoanRecords.
   */
  data: Prisma.BookLoanRecordCreateManyInput | Prisma.BookLoanRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BookLoanRecord createManyAndReturn
 */
export type BookLoanRecordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * The data used to create many BookLoanRecords.
   */
  data: Prisma.BookLoanRecordCreateManyInput | Prisma.BookLoanRecordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BookLoanRecord update
 */
export type BookLoanRecordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a BookLoanRecord.
   */
  data: Prisma.XOR<Prisma.BookLoanRecordUpdateInput, Prisma.BookLoanRecordUncheckedUpdateInput>
  /**
   * Choose, which BookLoanRecord to update.
   */
  where: Prisma.BookLoanRecordWhereUniqueInput
}

/**
 * BookLoanRecord updateMany
 */
export type BookLoanRecordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BookLoanRecords.
   */
  data: Prisma.XOR<Prisma.BookLoanRecordUpdateManyMutationInput, Prisma.BookLoanRecordUncheckedUpdateManyInput>
  /**
   * Filter which BookLoanRecords to update
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * Limit how many BookLoanRecords to update.
   */
  limit?: number
}

/**
 * BookLoanRecord updateManyAndReturn
 */
export type BookLoanRecordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * The data used to update BookLoanRecords.
   */
  data: Prisma.XOR<Prisma.BookLoanRecordUpdateManyMutationInput, Prisma.BookLoanRecordUncheckedUpdateManyInput>
  /**
   * Filter which BookLoanRecords to update
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * Limit how many BookLoanRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BookLoanRecord upsert
 */
export type BookLoanRecordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the BookLoanRecord to update in case it exists.
   */
  where: Prisma.BookLoanRecordWhereUniqueInput
  /**
   * In case the BookLoanRecord found by the `where` argument doesn't exist, create a new BookLoanRecord with this data.
   */
  create: Prisma.XOR<Prisma.BookLoanRecordCreateInput, Prisma.BookLoanRecordUncheckedCreateInput>
  /**
   * In case the BookLoanRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BookLoanRecordUpdateInput, Prisma.BookLoanRecordUncheckedUpdateInput>
}

/**
 * BookLoanRecord delete
 */
export type BookLoanRecordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
  /**
   * Filter which BookLoanRecord to delete.
   */
  where: Prisma.BookLoanRecordWhereUniqueInput
}

/**
 * BookLoanRecord deleteMany
 */
export type BookLoanRecordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BookLoanRecords to delete
   */
  where?: Prisma.BookLoanRecordWhereInput
  /**
   * Limit how many BookLoanRecords to delete.
   */
  limit?: number
}

/**
 * BookLoanRecord without action
 */
export type BookLoanRecordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookLoanRecord
   */
  select?: Prisma.BookLoanRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookLoanRecord
   */
  omit?: Prisma.BookLoanRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookLoanRecordInclude<ExtArgs> | null
}
