
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TokenVaultOAuthAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TokenVaultOAuthAccount
 * 
 */
export type TokenVaultOAuthAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$TokenVaultOAuthAccountPayload>

export type AggregateTokenVaultOAuthAccount = {
  _count: TokenVaultOAuthAccountCountAggregateOutputType | null
  _min: TokenVaultOAuthAccountMinAggregateOutputType | null
  _max: TokenVaultOAuthAccountMaxAggregateOutputType | null
}

export type TokenVaultOAuthAccountMinAggregateOutputType = {
  id: string | null
  provider: string | null
  email: string | null
  externalId: string | null
  name: string | null
  givenName: string | null
  familyName: string | null
  pictureUrl: string | null
  locale: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type TokenVaultOAuthAccountMaxAggregateOutputType = {
  id: string | null
  provider: string | null
  email: string | null
  externalId: string | null
  name: string | null
  givenName: string | null
  familyName: string | null
  pictureUrl: string | null
  locale: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type TokenVaultOAuthAccountCountAggregateOutputType = {
  id: number
  provider: number
  email: number
  externalId: number
  name: number
  givenName: number
  familyName: number
  pictureUrl: number
  locale: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type TokenVaultOAuthAccountMinAggregateInputType = {
  id?: true
  provider?: true
  email?: true
  externalId?: true
  name?: true
  givenName?: true
  familyName?: true
  pictureUrl?: true
  locale?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type TokenVaultOAuthAccountMaxAggregateInputType = {
  id?: true
  provider?: true
  email?: true
  externalId?: true
  name?: true
  givenName?: true
  familyName?: true
  pictureUrl?: true
  locale?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type TokenVaultOAuthAccountCountAggregateInputType = {
  id?: true
  provider?: true
  email?: true
  externalId?: true
  name?: true
  givenName?: true
  familyName?: true
  pictureUrl?: true
  locale?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type TokenVaultOAuthAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TokenVaultOAuthAccount to aggregate.
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthAccounts to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthAccountOrderByWithRelationInput | Prisma.TokenVaultOAuthAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TokenVaultOAuthAccounts
  **/
  _count?: true | TokenVaultOAuthAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TokenVaultOAuthAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TokenVaultOAuthAccountMaxAggregateInputType
}

export type GetTokenVaultOAuthAccountAggregateType<T extends TokenVaultOAuthAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateTokenVaultOAuthAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTokenVaultOAuthAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateTokenVaultOAuthAccount[P]>
}




export type TokenVaultOAuthAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  orderBy?: Prisma.TokenVaultOAuthAccountOrderByWithAggregationInput | Prisma.TokenVaultOAuthAccountOrderByWithAggregationInput[]
  by: Prisma.TokenVaultOAuthAccountScalarFieldEnum[] | Prisma.TokenVaultOAuthAccountScalarFieldEnum
  having?: Prisma.TokenVaultOAuthAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TokenVaultOAuthAccountCountAggregateInputType | true
  _min?: TokenVaultOAuthAccountMinAggregateInputType
  _max?: TokenVaultOAuthAccountMaxAggregateInputType
}

export type TokenVaultOAuthAccountGroupByOutputType = {
  id: string
  provider: string
  email: string
  externalId: string | null
  name: string | null
  givenName: string | null
  familyName: string | null
  pictureUrl: string | null
  locale: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: TokenVaultOAuthAccountCountAggregateOutputType | null
  _min: TokenVaultOAuthAccountMinAggregateOutputType | null
  _max: TokenVaultOAuthAccountMaxAggregateOutputType | null
}

export type GetTokenVaultOAuthAccountGroupByPayload<T extends TokenVaultOAuthAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TokenVaultOAuthAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TokenVaultOAuthAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TokenVaultOAuthAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TokenVaultOAuthAccountGroupByOutputType[P]>
      }
    >
  >



export type TokenVaultOAuthAccountWhereInput = {
  AND?: Prisma.TokenVaultOAuthAccountWhereInput | Prisma.TokenVaultOAuthAccountWhereInput[]
  OR?: Prisma.TokenVaultOAuthAccountWhereInput[]
  NOT?: Prisma.TokenVaultOAuthAccountWhereInput | Prisma.TokenVaultOAuthAccountWhereInput[]
  id?: Prisma.StringFilter<"TokenVaultOAuthAccount"> | string
  provider?: Prisma.StringFilter<"TokenVaultOAuthAccount"> | string
  email?: Prisma.StringFilter<"TokenVaultOAuthAccount"> | string
  externalId?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  name?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  givenName?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  familyName?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  pictureUrl?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  locale?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TokenVaultOAuthAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TokenVaultOAuthAccount"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"TokenVaultOAuthAccount"> | Date | string | null
  tokens?: Prisma.TokenVaultOAuthTokenListRelationFilter
}

export type TokenVaultOAuthAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  externalId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  givenName?: Prisma.SortOrderInput | Prisma.SortOrder
  familyName?: Prisma.SortOrderInput | Prisma.SortOrder
  pictureUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  locale?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  tokens?: Prisma.TokenVaultOAuthTokenOrderByRelationAggregateInput
}

export type TokenVaultOAuthAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  provider_email?: Prisma.TokenVaultOAuthAccountProviderEmailCompoundUniqueInput
  AND?: Prisma.TokenVaultOAuthAccountWhereInput | Prisma.TokenVaultOAuthAccountWhereInput[]
  OR?: Prisma.TokenVaultOAuthAccountWhereInput[]
  NOT?: Prisma.TokenVaultOAuthAccountWhereInput | Prisma.TokenVaultOAuthAccountWhereInput[]
  provider?: Prisma.StringFilter<"TokenVaultOAuthAccount"> | string
  email?: Prisma.StringFilter<"TokenVaultOAuthAccount"> | string
  externalId?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  name?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  givenName?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  familyName?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  pictureUrl?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  locale?: Prisma.StringNullableFilter<"TokenVaultOAuthAccount"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TokenVaultOAuthAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TokenVaultOAuthAccount"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"TokenVaultOAuthAccount"> | Date | string | null
  tokens?: Prisma.TokenVaultOAuthTokenListRelationFilter
}, "id" | "provider_email">

export type TokenVaultOAuthAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  externalId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  givenName?: Prisma.SortOrderInput | Prisma.SortOrder
  familyName?: Prisma.SortOrderInput | Prisma.SortOrder
  pictureUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  locale?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TokenVaultOAuthAccountCountOrderByAggregateInput
  _max?: Prisma.TokenVaultOAuthAccountMaxOrderByAggregateInput
  _min?: Prisma.TokenVaultOAuthAccountMinOrderByAggregateInput
}

export type TokenVaultOAuthAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.TokenVaultOAuthAccountScalarWhereWithAggregatesInput | Prisma.TokenVaultOAuthAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.TokenVaultOAuthAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TokenVaultOAuthAccountScalarWhereWithAggregatesInput | Prisma.TokenVaultOAuthAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthAccount"> | string
  provider?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthAccount"> | string
  email?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthAccount"> | string
  externalId?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | string | null
  name?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | string | null
  givenName?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | string | null
  familyName?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | string | null
  pictureUrl?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | string | null
  locale?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TokenVaultOAuthAccount"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TokenVaultOAuthAccount"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TokenVaultOAuthAccount"> | Date | string | null
}

export type TokenVaultOAuthAccountCreateInput = {
  id?: string
  provider: string
  email: string
  externalId?: string | null
  name?: string | null
  givenName?: string | null
  familyName?: string | null
  pictureUrl?: string | null
  locale?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  tokens?: Prisma.TokenVaultOAuthTokenCreateNestedManyWithoutAccountInput
}

export type TokenVaultOAuthAccountUncheckedCreateInput = {
  id?: string
  provider: string
  email: string
  externalId?: string | null
  name?: string | null
  givenName?: string | null
  familyName?: string | null
  pictureUrl?: string | null
  locale?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  tokens?: Prisma.TokenVaultOAuthTokenUncheckedCreateNestedManyWithoutAccountInput
}

export type TokenVaultOAuthAccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  givenName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  familyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pictureUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tokens?: Prisma.TokenVaultOAuthTokenUpdateManyWithoutAccountNestedInput
}

export type TokenVaultOAuthAccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  givenName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  familyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pictureUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tokens?: Prisma.TokenVaultOAuthTokenUncheckedUpdateManyWithoutAccountNestedInput
}

export type TokenVaultOAuthAccountCreateManyInput = {
  id?: string
  provider: string
  email: string
  externalId?: string | null
  name?: string | null
  givenName?: string | null
  familyName?: string | null
  pictureUrl?: string | null
  locale?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TokenVaultOAuthAccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  givenName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  familyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pictureUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TokenVaultOAuthAccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  givenName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  familyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pictureUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TokenVaultOAuthAccountProviderEmailCompoundUniqueInput = {
  provider: string
  email: string
}

export type TokenVaultOAuthAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  givenName?: Prisma.SortOrder
  familyName?: Prisma.SortOrder
  pictureUrl?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TokenVaultOAuthAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  givenName?: Prisma.SortOrder
  familyName?: Prisma.SortOrder
  pictureUrl?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TokenVaultOAuthAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  givenName?: Prisma.SortOrder
  familyName?: Prisma.SortOrder
  pictureUrl?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TokenVaultOAuthAccountScalarRelationFilter = {
  is?: Prisma.TokenVaultOAuthAccountWhereInput
  isNot?: Prisma.TokenVaultOAuthAccountWhereInput
}

export type TokenVaultOAuthAccountCreateNestedOneWithoutTokensInput = {
  create?: Prisma.XOR<Prisma.TokenVaultOAuthAccountCreateWithoutTokensInput, Prisma.TokenVaultOAuthAccountUncheckedCreateWithoutTokensInput>
  connectOrCreate?: Prisma.TokenVaultOAuthAccountCreateOrConnectWithoutTokensInput
  connect?: Prisma.TokenVaultOAuthAccountWhereUniqueInput
}

export type TokenVaultOAuthAccountUpdateOneRequiredWithoutTokensNestedInput = {
  create?: Prisma.XOR<Prisma.TokenVaultOAuthAccountCreateWithoutTokensInput, Prisma.TokenVaultOAuthAccountUncheckedCreateWithoutTokensInput>
  connectOrCreate?: Prisma.TokenVaultOAuthAccountCreateOrConnectWithoutTokensInput
  upsert?: Prisma.TokenVaultOAuthAccountUpsertWithoutTokensInput
  connect?: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateToOneWithWhereWithoutTokensInput, Prisma.TokenVaultOAuthAccountUpdateWithoutTokensInput>, Prisma.TokenVaultOAuthAccountUncheckedUpdateWithoutTokensInput>
}

export type TokenVaultOAuthAccountCreateWithoutTokensInput = {
  id?: string
  provider: string
  email: string
  externalId?: string | null
  name?: string | null
  givenName?: string | null
  familyName?: string | null
  pictureUrl?: string | null
  locale?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TokenVaultOAuthAccountUncheckedCreateWithoutTokensInput = {
  id?: string
  provider: string
  email: string
  externalId?: string | null
  name?: string | null
  givenName?: string | null
  familyName?: string | null
  pictureUrl?: string | null
  locale?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TokenVaultOAuthAccountCreateOrConnectWithoutTokensInput = {
  where: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.TokenVaultOAuthAccountCreateWithoutTokensInput, Prisma.TokenVaultOAuthAccountUncheckedCreateWithoutTokensInput>
}

export type TokenVaultOAuthAccountUpsertWithoutTokensInput = {
  update: Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateWithoutTokensInput, Prisma.TokenVaultOAuthAccountUncheckedUpdateWithoutTokensInput>
  create: Prisma.XOR<Prisma.TokenVaultOAuthAccountCreateWithoutTokensInput, Prisma.TokenVaultOAuthAccountUncheckedCreateWithoutTokensInput>
  where?: Prisma.TokenVaultOAuthAccountWhereInput
}

export type TokenVaultOAuthAccountUpdateToOneWithWhereWithoutTokensInput = {
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  data: Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateWithoutTokensInput, Prisma.TokenVaultOAuthAccountUncheckedUpdateWithoutTokensInput>
}

export type TokenVaultOAuthAccountUpdateWithoutTokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  givenName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  familyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pictureUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TokenVaultOAuthAccountUncheckedUpdateWithoutTokensInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  givenName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  familyName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pictureUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  locale?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type TokenVaultOAuthAccountCountOutputType
 */

export type TokenVaultOAuthAccountCountOutputType = {
  tokens: number
}

export type TokenVaultOAuthAccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tokens?: boolean | TokenVaultOAuthAccountCountOutputTypeCountTokensArgs
}

/**
 * TokenVaultOAuthAccountCountOutputType without action
 */
export type TokenVaultOAuthAccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccountCountOutputType
   */
  select?: Prisma.TokenVaultOAuthAccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TokenVaultOAuthAccountCountOutputType without action
 */
export type TokenVaultOAuthAccountCountOutputTypeCountTokensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TokenVaultOAuthTokenWhereInput
}


export type TokenVaultOAuthAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  provider?: boolean
  email?: boolean
  externalId?: boolean
  name?: boolean
  givenName?: boolean
  familyName?: boolean
  pictureUrl?: boolean
  locale?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  tokens?: boolean | Prisma.TokenVaultOAuthAccount$tokensArgs<ExtArgs>
  _count?: boolean | Prisma.TokenVaultOAuthAccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tokenVaultOAuthAccount"]>

export type TokenVaultOAuthAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  provider?: boolean
  email?: boolean
  externalId?: boolean
  name?: boolean
  givenName?: boolean
  familyName?: boolean
  pictureUrl?: boolean
  locale?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["tokenVaultOAuthAccount"]>

export type TokenVaultOAuthAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  provider?: boolean
  email?: boolean
  externalId?: boolean
  name?: boolean
  givenName?: boolean
  familyName?: boolean
  pictureUrl?: boolean
  locale?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["tokenVaultOAuthAccount"]>

export type TokenVaultOAuthAccountSelectScalar = {
  id?: boolean
  provider?: boolean
  email?: boolean
  externalId?: boolean
  name?: boolean
  givenName?: boolean
  familyName?: boolean
  pictureUrl?: boolean
  locale?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type TokenVaultOAuthAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "provider" | "email" | "externalId" | "name" | "givenName" | "familyName" | "pictureUrl" | "locale" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["tokenVaultOAuthAccount"]>
export type TokenVaultOAuthAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tokens?: boolean | Prisma.TokenVaultOAuthAccount$tokensArgs<ExtArgs>
  _count?: boolean | Prisma.TokenVaultOAuthAccountCountOutputTypeDefaultArgs<ExtArgs>
}
export type TokenVaultOAuthAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TokenVaultOAuthAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TokenVaultOAuthAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TokenVaultOAuthAccount"
  objects: {
    tokens: Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    provider: string
    email: string
    externalId: string | null
    name: string | null
    givenName: string | null
    familyName: string | null
    pictureUrl: string | null
    locale: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["tokenVaultOAuthAccount"]>
  composites: {}
}

export type TokenVaultOAuthAccountGetPayload<S extends boolean | null | undefined | TokenVaultOAuthAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload, S>

export type TokenVaultOAuthAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TokenVaultOAuthAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TokenVaultOAuthAccountCountAggregateInputType | true
  }

export interface TokenVaultOAuthAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TokenVaultOAuthAccount'], meta: { name: 'TokenVaultOAuthAccount' } }
  /**
   * Find zero or one TokenVaultOAuthAccount that matches the filter.
   * @param {TokenVaultOAuthAccountFindUniqueArgs} args - Arguments to find a TokenVaultOAuthAccount
   * @example
   * // Get one TokenVaultOAuthAccount
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TokenVaultOAuthAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TokenVaultOAuthAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TokenVaultOAuthAccountFindUniqueOrThrowArgs} args - Arguments to find a TokenVaultOAuthAccount
   * @example
   * // Get one TokenVaultOAuthAccount
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TokenVaultOAuthAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TokenVaultOAuthAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountFindFirstArgs} args - Arguments to find a TokenVaultOAuthAccount
   * @example
   * // Get one TokenVaultOAuthAccount
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TokenVaultOAuthAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TokenVaultOAuthAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountFindFirstOrThrowArgs} args - Arguments to find a TokenVaultOAuthAccount
   * @example
   * // Get one TokenVaultOAuthAccount
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TokenVaultOAuthAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TokenVaultOAuthAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TokenVaultOAuthAccounts
   * const tokenVaultOAuthAccounts = await prisma.tokenVaultOAuthAccount.findMany()
   * 
   * // Get first 10 TokenVaultOAuthAccounts
   * const tokenVaultOAuthAccounts = await prisma.tokenVaultOAuthAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tokenVaultOAuthAccountWithIdOnly = await prisma.tokenVaultOAuthAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TokenVaultOAuthAccountFindManyArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TokenVaultOAuthAccount.
   * @param {TokenVaultOAuthAccountCreateArgs} args - Arguments to create a TokenVaultOAuthAccount.
   * @example
   * // Create one TokenVaultOAuthAccount
   * const TokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.create({
   *   data: {
   *     // ... data to create a TokenVaultOAuthAccount
   *   }
   * })
   * 
   */
  create<T extends TokenVaultOAuthAccountCreateArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountCreateArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TokenVaultOAuthAccounts.
   * @param {TokenVaultOAuthAccountCreateManyArgs} args - Arguments to create many TokenVaultOAuthAccounts.
   * @example
   * // Create many TokenVaultOAuthAccounts
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TokenVaultOAuthAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TokenVaultOAuthAccounts and returns the data saved in the database.
   * @param {TokenVaultOAuthAccountCreateManyAndReturnArgs} args - Arguments to create many TokenVaultOAuthAccounts.
   * @example
   * // Create many TokenVaultOAuthAccounts
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TokenVaultOAuthAccounts and only return the `id`
   * const tokenVaultOAuthAccountWithIdOnly = await prisma.tokenVaultOAuthAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TokenVaultOAuthAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TokenVaultOAuthAccount.
   * @param {TokenVaultOAuthAccountDeleteArgs} args - Arguments to delete one TokenVaultOAuthAccount.
   * @example
   * // Delete one TokenVaultOAuthAccount
   * const TokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.delete({
   *   where: {
   *     // ... filter to delete one TokenVaultOAuthAccount
   *   }
   * })
   * 
   */
  delete<T extends TokenVaultOAuthAccountDeleteArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TokenVaultOAuthAccount.
   * @param {TokenVaultOAuthAccountUpdateArgs} args - Arguments to update one TokenVaultOAuthAccount.
   * @example
   * // Update one TokenVaultOAuthAccount
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TokenVaultOAuthAccountUpdateArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TokenVaultOAuthAccounts.
   * @param {TokenVaultOAuthAccountDeleteManyArgs} args - Arguments to filter TokenVaultOAuthAccounts to delete.
   * @example
   * // Delete a few TokenVaultOAuthAccounts
   * const { count } = await prisma.tokenVaultOAuthAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TokenVaultOAuthAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TokenVaultOAuthAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TokenVaultOAuthAccounts
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TokenVaultOAuthAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TokenVaultOAuthAccounts and returns the data updated in the database.
   * @param {TokenVaultOAuthAccountUpdateManyAndReturnArgs} args - Arguments to update many TokenVaultOAuthAccounts.
   * @example
   * // Update many TokenVaultOAuthAccounts
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TokenVaultOAuthAccounts and only return the `id`
   * const tokenVaultOAuthAccountWithIdOnly = await prisma.tokenVaultOAuthAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TokenVaultOAuthAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TokenVaultOAuthAccount.
   * @param {TokenVaultOAuthAccountUpsertArgs} args - Arguments to update or create a TokenVaultOAuthAccount.
   * @example
   * // Update or create a TokenVaultOAuthAccount
   * const tokenVaultOAuthAccount = await prisma.tokenVaultOAuthAccount.upsert({
   *   create: {
   *     // ... data to create a TokenVaultOAuthAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TokenVaultOAuthAccount we want to update
   *   }
   * })
   */
  upsert<T extends TokenVaultOAuthAccountUpsertArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TokenVaultOAuthAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountCountArgs} args - Arguments to filter TokenVaultOAuthAccounts to count.
   * @example
   * // Count the number of TokenVaultOAuthAccounts
   * const count = await prisma.tokenVaultOAuthAccount.count({
   *   where: {
   *     // ... the filter for the TokenVaultOAuthAccounts we want to count
   *   }
   * })
  **/
  count<T extends TokenVaultOAuthAccountCountArgs>(
    args?: Prisma.Subset<T, TokenVaultOAuthAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TokenVaultOAuthAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TokenVaultOAuthAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TokenVaultOAuthAccountAggregateArgs>(args: Prisma.Subset<T, TokenVaultOAuthAccountAggregateArgs>): Prisma.PrismaPromise<GetTokenVaultOAuthAccountAggregateType<T>>

  /**
   * Group by TokenVaultOAuthAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TokenVaultOAuthAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TokenVaultOAuthAccountGroupByArgs['orderBy'] }
      : { orderBy?: TokenVaultOAuthAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TokenVaultOAuthAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTokenVaultOAuthAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TokenVaultOAuthAccount model
 */
readonly fields: TokenVaultOAuthAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TokenVaultOAuthAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TokenVaultOAuthAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tokens<T extends Prisma.TokenVaultOAuthAccount$tokensArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TokenVaultOAuthAccount$tokensArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TokenVaultOAuthAccount model
 */
export interface TokenVaultOAuthAccountFieldRefs {
  readonly id: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly provider: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly email: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly externalId: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly name: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly givenName: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly familyName: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly pictureUrl: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly locale: Prisma.FieldRef<"TokenVaultOAuthAccount", 'String'>
  readonly createdAt: Prisma.FieldRef<"TokenVaultOAuthAccount", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TokenVaultOAuthAccount", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"TokenVaultOAuthAccount", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TokenVaultOAuthAccount findUnique
 */
export type TokenVaultOAuthAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthAccount to fetch.
   */
  where: Prisma.TokenVaultOAuthAccountWhereUniqueInput
}

/**
 * TokenVaultOAuthAccount findUniqueOrThrow
 */
export type TokenVaultOAuthAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthAccount to fetch.
   */
  where: Prisma.TokenVaultOAuthAccountWhereUniqueInput
}

/**
 * TokenVaultOAuthAccount findFirst
 */
export type TokenVaultOAuthAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthAccount to fetch.
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthAccounts to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthAccountOrderByWithRelationInput | Prisma.TokenVaultOAuthAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TokenVaultOAuthAccounts.
   */
  cursor?: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenVaultOAuthAccounts.
   */
  distinct?: Prisma.TokenVaultOAuthAccountScalarFieldEnum | Prisma.TokenVaultOAuthAccountScalarFieldEnum[]
}

/**
 * TokenVaultOAuthAccount findFirstOrThrow
 */
export type TokenVaultOAuthAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthAccount to fetch.
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthAccounts to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthAccountOrderByWithRelationInput | Prisma.TokenVaultOAuthAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TokenVaultOAuthAccounts.
   */
  cursor?: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenVaultOAuthAccounts.
   */
  distinct?: Prisma.TokenVaultOAuthAccountScalarFieldEnum | Prisma.TokenVaultOAuthAccountScalarFieldEnum[]
}

/**
 * TokenVaultOAuthAccount findMany
 */
export type TokenVaultOAuthAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthAccounts to fetch.
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthAccounts to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthAccountOrderByWithRelationInput | Prisma.TokenVaultOAuthAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TokenVaultOAuthAccounts.
   */
  cursor?: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenVaultOAuthAccounts.
   */
  distinct?: Prisma.TokenVaultOAuthAccountScalarFieldEnum | Prisma.TokenVaultOAuthAccountScalarFieldEnum[]
}

/**
 * TokenVaultOAuthAccount create
 */
export type TokenVaultOAuthAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a TokenVaultOAuthAccount.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthAccountCreateInput, Prisma.TokenVaultOAuthAccountUncheckedCreateInput>
}

/**
 * TokenVaultOAuthAccount createMany
 */
export type TokenVaultOAuthAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TokenVaultOAuthAccounts.
   */
  data: Prisma.TokenVaultOAuthAccountCreateManyInput | Prisma.TokenVaultOAuthAccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TokenVaultOAuthAccount createManyAndReturn
 */
export type TokenVaultOAuthAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * The data used to create many TokenVaultOAuthAccounts.
   */
  data: Prisma.TokenVaultOAuthAccountCreateManyInput | Prisma.TokenVaultOAuthAccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TokenVaultOAuthAccount update
 */
export type TokenVaultOAuthAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a TokenVaultOAuthAccount.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateInput, Prisma.TokenVaultOAuthAccountUncheckedUpdateInput>
  /**
   * Choose, which TokenVaultOAuthAccount to update.
   */
  where: Prisma.TokenVaultOAuthAccountWhereUniqueInput
}

/**
 * TokenVaultOAuthAccount updateMany
 */
export type TokenVaultOAuthAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TokenVaultOAuthAccounts.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateManyMutationInput, Prisma.TokenVaultOAuthAccountUncheckedUpdateManyInput>
  /**
   * Filter which TokenVaultOAuthAccounts to update
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * Limit how many TokenVaultOAuthAccounts to update.
   */
  limit?: number
}

/**
 * TokenVaultOAuthAccount updateManyAndReturn
 */
export type TokenVaultOAuthAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * The data used to update TokenVaultOAuthAccounts.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateManyMutationInput, Prisma.TokenVaultOAuthAccountUncheckedUpdateManyInput>
  /**
   * Filter which TokenVaultOAuthAccounts to update
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * Limit how many TokenVaultOAuthAccounts to update.
   */
  limit?: number
}

/**
 * TokenVaultOAuthAccount upsert
 */
export type TokenVaultOAuthAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the TokenVaultOAuthAccount to update in case it exists.
   */
  where: Prisma.TokenVaultOAuthAccountWhereUniqueInput
  /**
   * In case the TokenVaultOAuthAccount found by the `where` argument doesn't exist, create a new TokenVaultOAuthAccount with this data.
   */
  create: Prisma.XOR<Prisma.TokenVaultOAuthAccountCreateInput, Prisma.TokenVaultOAuthAccountUncheckedCreateInput>
  /**
   * In case the TokenVaultOAuthAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TokenVaultOAuthAccountUpdateInput, Prisma.TokenVaultOAuthAccountUncheckedUpdateInput>
}

/**
 * TokenVaultOAuthAccount delete
 */
export type TokenVaultOAuthAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
  /**
   * Filter which TokenVaultOAuthAccount to delete.
   */
  where: Prisma.TokenVaultOAuthAccountWhereUniqueInput
}

/**
 * TokenVaultOAuthAccount deleteMany
 */
export type TokenVaultOAuthAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TokenVaultOAuthAccounts to delete
   */
  where?: Prisma.TokenVaultOAuthAccountWhereInput
  /**
   * Limit how many TokenVaultOAuthAccounts to delete.
   */
  limit?: number
}

/**
 * TokenVaultOAuthAccount.tokens
 */
export type TokenVaultOAuthAccount$tokensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  orderBy?: Prisma.TokenVaultOAuthTokenOrderByWithRelationInput | Prisma.TokenVaultOAuthTokenOrderByWithRelationInput[]
  cursor?: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TokenVaultOAuthTokenScalarFieldEnum | Prisma.TokenVaultOAuthTokenScalarFieldEnum[]
}

/**
 * TokenVaultOAuthAccount without action
 */
export type TokenVaultOAuthAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthAccount
   */
  select?: Prisma.TokenVaultOAuthAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthAccount
   */
  omit?: Prisma.TokenVaultOAuthAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthAccountInclude<ExtArgs> | null
}
