
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TokenVaultOAuthToken` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TokenVaultOAuthToken
 * 
 */
export type TokenVaultOAuthTokenModel = runtime.Types.Result.DefaultSelection<Prisma.$TokenVaultOAuthTokenPayload>

export type AggregateTokenVaultOAuthToken = {
  _count: TokenVaultOAuthTokenCountAggregateOutputType | null
  _min: TokenVaultOAuthTokenMinAggregateOutputType | null
  _max: TokenVaultOAuthTokenMaxAggregateOutputType | null
}

export type TokenVaultOAuthTokenMinAggregateOutputType = {
  id: string | null
  accountId: string | null
  clientId: string | null
  provider: string | null
  email: string | null
  ownerSub: string | null
  accessToken: string | null
  refreshToken: string | null
  tokenType: string | null
  expiresAt: Date | null
  scope: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TokenVaultOAuthTokenMaxAggregateOutputType = {
  id: string | null
  accountId: string | null
  clientId: string | null
  provider: string | null
  email: string | null
  ownerSub: string | null
  accessToken: string | null
  refreshToken: string | null
  tokenType: string | null
  expiresAt: Date | null
  scope: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TokenVaultOAuthTokenCountAggregateOutputType = {
  id: number
  accountId: number
  clientId: number
  provider: number
  email: number
  ownerSub: number
  accessToken: number
  refreshToken: number
  tokenType: number
  expiresAt: number
  scope: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TokenVaultOAuthTokenMinAggregateInputType = {
  id?: true
  accountId?: true
  clientId?: true
  provider?: true
  email?: true
  ownerSub?: true
  accessToken?: true
  refreshToken?: true
  tokenType?: true
  expiresAt?: true
  scope?: true
  createdAt?: true
  updatedAt?: true
}

export type TokenVaultOAuthTokenMaxAggregateInputType = {
  id?: true
  accountId?: true
  clientId?: true
  provider?: true
  email?: true
  ownerSub?: true
  accessToken?: true
  refreshToken?: true
  tokenType?: true
  expiresAt?: true
  scope?: true
  createdAt?: true
  updatedAt?: true
}

export type TokenVaultOAuthTokenCountAggregateInputType = {
  id?: true
  accountId?: true
  clientId?: true
  provider?: true
  email?: true
  ownerSub?: true
  accessToken?: true
  refreshToken?: true
  tokenType?: true
  expiresAt?: true
  scope?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TokenVaultOAuthTokenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TokenVaultOAuthToken to aggregate.
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthTokens to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthTokenOrderByWithRelationInput | Prisma.TokenVaultOAuthTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TokenVaultOAuthTokens
  **/
  _count?: true | TokenVaultOAuthTokenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TokenVaultOAuthTokenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TokenVaultOAuthTokenMaxAggregateInputType
}

export type GetTokenVaultOAuthTokenAggregateType<T extends TokenVaultOAuthTokenAggregateArgs> = {
      [P in keyof T & keyof AggregateTokenVaultOAuthToken]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTokenVaultOAuthToken[P]>
    : Prisma.GetScalarType<T[P], AggregateTokenVaultOAuthToken[P]>
}




export type TokenVaultOAuthTokenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  orderBy?: Prisma.TokenVaultOAuthTokenOrderByWithAggregationInput | Prisma.TokenVaultOAuthTokenOrderByWithAggregationInput[]
  by: Prisma.TokenVaultOAuthTokenScalarFieldEnum[] | Prisma.TokenVaultOAuthTokenScalarFieldEnum
  having?: Prisma.TokenVaultOAuthTokenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TokenVaultOAuthTokenCountAggregateInputType | true
  _min?: TokenVaultOAuthTokenMinAggregateInputType
  _max?: TokenVaultOAuthTokenMaxAggregateInputType
}

export type TokenVaultOAuthTokenGroupByOutputType = {
  id: string
  accountId: string
  clientId: string
  provider: string
  email: string
  ownerSub: string | null
  accessToken: string
  refreshToken: string | null
  tokenType: string | null
  expiresAt: Date | null
  scope: string | null
  createdAt: Date
  updatedAt: Date
  _count: TokenVaultOAuthTokenCountAggregateOutputType | null
  _min: TokenVaultOAuthTokenMinAggregateOutputType | null
  _max: TokenVaultOAuthTokenMaxAggregateOutputType | null
}

export type GetTokenVaultOAuthTokenGroupByPayload<T extends TokenVaultOAuthTokenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TokenVaultOAuthTokenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TokenVaultOAuthTokenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TokenVaultOAuthTokenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TokenVaultOAuthTokenGroupByOutputType[P]>
      }
    >
  >



export type TokenVaultOAuthTokenWhereInput = {
  AND?: Prisma.TokenVaultOAuthTokenWhereInput | Prisma.TokenVaultOAuthTokenWhereInput[]
  OR?: Prisma.TokenVaultOAuthTokenWhereInput[]
  NOT?: Prisma.TokenVaultOAuthTokenWhereInput | Prisma.TokenVaultOAuthTokenWhereInput[]
  id?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  accountId?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  clientId?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  provider?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  email?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  ownerSub?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  accessToken?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  refreshToken?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  tokenType?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"TokenVaultOAuthToken"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TokenVaultOAuthToken"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TokenVaultOAuthToken"> | Date | string
  account?: Prisma.XOR<Prisma.TokenVaultOAuthAccountScalarRelationFilter, Prisma.TokenVaultOAuthAccountWhereInput>
}

export type TokenVaultOAuthTokenOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ownerSub?: Prisma.SortOrderInput | Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrderInput | Prisma.SortOrder
  tokenType?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  account?: Prisma.TokenVaultOAuthAccountOrderByWithRelationInput
}

export type TokenVaultOAuthTokenWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  accountId_clientId?: Prisma.TokenVaultOAuthTokenAccountIdClientIdCompoundUniqueInput
  AND?: Prisma.TokenVaultOAuthTokenWhereInput | Prisma.TokenVaultOAuthTokenWhereInput[]
  OR?: Prisma.TokenVaultOAuthTokenWhereInput[]
  NOT?: Prisma.TokenVaultOAuthTokenWhereInput | Prisma.TokenVaultOAuthTokenWhereInput[]
  accountId?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  clientId?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  provider?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  email?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  ownerSub?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  accessToken?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  refreshToken?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  tokenType?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"TokenVaultOAuthToken"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TokenVaultOAuthToken"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TokenVaultOAuthToken"> | Date | string
  account?: Prisma.XOR<Prisma.TokenVaultOAuthAccountScalarRelationFilter, Prisma.TokenVaultOAuthAccountWhereInput>
}, "id" | "accountId_clientId">

export type TokenVaultOAuthTokenOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ownerSub?: Prisma.SortOrderInput | Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrderInput | Prisma.SortOrder
  tokenType?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TokenVaultOAuthTokenCountOrderByAggregateInput
  _max?: Prisma.TokenVaultOAuthTokenMaxOrderByAggregateInput
  _min?: Prisma.TokenVaultOAuthTokenMinOrderByAggregateInput
}

export type TokenVaultOAuthTokenScalarWhereWithAggregatesInput = {
  AND?: Prisma.TokenVaultOAuthTokenScalarWhereWithAggregatesInput | Prisma.TokenVaultOAuthTokenScalarWhereWithAggregatesInput[]
  OR?: Prisma.TokenVaultOAuthTokenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TokenVaultOAuthTokenScalarWhereWithAggregatesInput | Prisma.TokenVaultOAuthTokenScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthToken"> | string
  accountId?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthToken"> | string
  clientId?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthToken"> | string
  provider?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthToken"> | string
  email?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthToken"> | string
  ownerSub?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthToken"> | string | null
  accessToken?: Prisma.StringWithAggregatesFilter<"TokenVaultOAuthToken"> | string
  refreshToken?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthToken"> | string | null
  tokenType?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthToken"> | string | null
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TokenVaultOAuthToken"> | Date | string | null
  scope?: Prisma.StringNullableWithAggregatesFilter<"TokenVaultOAuthToken"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TokenVaultOAuthToken"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TokenVaultOAuthToken"> | Date | string
}

export type TokenVaultOAuthTokenCreateInput = {
  id?: string
  clientId: string
  provider: string
  email: string
  ownerSub?: string | null
  accessToken: string
  refreshToken?: string | null
  tokenType?: string | null
  expiresAt?: Date | string | null
  scope?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.TokenVaultOAuthAccountCreateNestedOneWithoutTokensInput
}

export type TokenVaultOAuthTokenUncheckedCreateInput = {
  id?: string
  accountId: string
  clientId: string
  provider: string
  email: string
  ownerSub?: string | null
  accessToken: string
  refreshToken?: string | null
  tokenType?: string | null
  expiresAt?: Date | string | null
  scope?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TokenVaultOAuthTokenUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.TokenVaultOAuthAccountUpdateOneRequiredWithoutTokensNestedInput
}

export type TokenVaultOAuthTokenUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenVaultOAuthTokenCreateManyInput = {
  id?: string
  accountId: string
  clientId: string
  provider: string
  email: string
  ownerSub?: string | null
  accessToken: string
  refreshToken?: string | null
  tokenType?: string | null
  expiresAt?: Date | string | null
  scope?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TokenVaultOAuthTokenUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenVaultOAuthTokenUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenVaultOAuthTokenListRelationFilter = {
  every?: Prisma.TokenVaultOAuthTokenWhereInput
  some?: Prisma.TokenVaultOAuthTokenWhereInput
  none?: Prisma.TokenVaultOAuthTokenWhereInput
}

export type TokenVaultOAuthTokenOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TokenVaultOAuthTokenAccountIdClientIdCompoundUniqueInput = {
  accountId: string
  clientId: string
}

export type TokenVaultOAuthTokenCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ownerSub?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  tokenType?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TokenVaultOAuthTokenMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ownerSub?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  tokenType?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TokenVaultOAuthTokenMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  email?: Prisma.SortOrder
  ownerSub?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  refreshToken?: Prisma.SortOrder
  tokenType?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TokenVaultOAuthTokenCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput> | Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput[] | Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput | Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.TokenVaultOAuthTokenCreateManyAccountInputEnvelope
  connect?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
}

export type TokenVaultOAuthTokenUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput> | Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput[] | Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput | Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.TokenVaultOAuthTokenCreateManyAccountInputEnvelope
  connect?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
}

export type TokenVaultOAuthTokenUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput> | Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput[] | Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput | Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.TokenVaultOAuthTokenUpsertWithWhereUniqueWithoutAccountInput | Prisma.TokenVaultOAuthTokenUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.TokenVaultOAuthTokenCreateManyAccountInputEnvelope
  set?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  disconnect?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  delete?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  connect?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  update?: Prisma.TokenVaultOAuthTokenUpdateWithWhereUniqueWithoutAccountInput | Prisma.TokenVaultOAuthTokenUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.TokenVaultOAuthTokenUpdateManyWithWhereWithoutAccountInput | Prisma.TokenVaultOAuthTokenUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.TokenVaultOAuthTokenScalarWhereInput | Prisma.TokenVaultOAuthTokenScalarWhereInput[]
}

export type TokenVaultOAuthTokenUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput> | Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput[] | Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput | Prisma.TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.TokenVaultOAuthTokenUpsertWithWhereUniqueWithoutAccountInput | Prisma.TokenVaultOAuthTokenUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.TokenVaultOAuthTokenCreateManyAccountInputEnvelope
  set?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  disconnect?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  delete?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  connect?: Prisma.TokenVaultOAuthTokenWhereUniqueInput | Prisma.TokenVaultOAuthTokenWhereUniqueInput[]
  update?: Prisma.TokenVaultOAuthTokenUpdateWithWhereUniqueWithoutAccountInput | Prisma.TokenVaultOAuthTokenUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.TokenVaultOAuthTokenUpdateManyWithWhereWithoutAccountInput | Prisma.TokenVaultOAuthTokenUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.TokenVaultOAuthTokenScalarWhereInput | Prisma.TokenVaultOAuthTokenScalarWhereInput[]
}

export type TokenVaultOAuthTokenCreateWithoutAccountInput = {
  id?: string
  clientId: string
  provider: string
  email: string
  ownerSub?: string | null
  accessToken: string
  refreshToken?: string | null
  tokenType?: string | null
  expiresAt?: Date | string | null
  scope?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput = {
  id?: string
  clientId: string
  provider: string
  email: string
  ownerSub?: string | null
  accessToken: string
  refreshToken?: string | null
  tokenType?: string | null
  expiresAt?: Date | string | null
  scope?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TokenVaultOAuthTokenCreateOrConnectWithoutAccountInput = {
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  create: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput>
}

export type TokenVaultOAuthTokenCreateManyAccountInputEnvelope = {
  data: Prisma.TokenVaultOAuthTokenCreateManyAccountInput | Prisma.TokenVaultOAuthTokenCreateManyAccountInput[]
  skipDuplicates?: boolean
}

export type TokenVaultOAuthTokenUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  update: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedCreateWithoutAccountInput>
}

export type TokenVaultOAuthTokenUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  data: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateWithoutAccountInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateWithoutAccountInput>
}

export type TokenVaultOAuthTokenUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.TokenVaultOAuthTokenScalarWhereInput
  data: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateManyMutationInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateManyWithoutAccountInput>
}

export type TokenVaultOAuthTokenScalarWhereInput = {
  AND?: Prisma.TokenVaultOAuthTokenScalarWhereInput | Prisma.TokenVaultOAuthTokenScalarWhereInput[]
  OR?: Prisma.TokenVaultOAuthTokenScalarWhereInput[]
  NOT?: Prisma.TokenVaultOAuthTokenScalarWhereInput | Prisma.TokenVaultOAuthTokenScalarWhereInput[]
  id?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  accountId?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  clientId?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  provider?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  email?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  ownerSub?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  accessToken?: Prisma.StringFilter<"TokenVaultOAuthToken"> | string
  refreshToken?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  tokenType?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"TokenVaultOAuthToken"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"TokenVaultOAuthToken"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TokenVaultOAuthToken"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TokenVaultOAuthToken"> | Date | string
}

export type TokenVaultOAuthTokenCreateManyAccountInput = {
  id?: string
  clientId: string
  provider: string
  email: string
  ownerSub?: string | null
  accessToken: string
  refreshToken?: string | null
  tokenType?: string | null
  expiresAt?: Date | string | null
  scope?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TokenVaultOAuthTokenUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenVaultOAuthTokenUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TokenVaultOAuthTokenUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  ownerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessToken?: Prisma.StringFieldUpdateOperationsInput | string
  refreshToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tokenType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TokenVaultOAuthTokenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  clientId?: boolean
  provider?: boolean
  email?: boolean
  ownerSub?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  tokenType?: boolean
  expiresAt?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tokenVaultOAuthToken"]>

export type TokenVaultOAuthTokenSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  clientId?: boolean
  provider?: boolean
  email?: boolean
  ownerSub?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  tokenType?: boolean
  expiresAt?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tokenVaultOAuthToken"]>

export type TokenVaultOAuthTokenSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  clientId?: boolean
  provider?: boolean
  email?: boolean
  ownerSub?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  tokenType?: boolean
  expiresAt?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tokenVaultOAuthToken"]>

export type TokenVaultOAuthTokenSelectScalar = {
  id?: boolean
  accountId?: boolean
  clientId?: boolean
  provider?: boolean
  email?: boolean
  ownerSub?: boolean
  accessToken?: boolean
  refreshToken?: boolean
  tokenType?: boolean
  expiresAt?: boolean
  scope?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TokenVaultOAuthTokenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accountId" | "clientId" | "provider" | "email" | "ownerSub" | "accessToken" | "refreshToken" | "tokenType" | "expiresAt" | "scope" | "createdAt" | "updatedAt", ExtArgs["result"]["tokenVaultOAuthToken"]>
export type TokenVaultOAuthTokenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>
}
export type TokenVaultOAuthTokenIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>
}
export type TokenVaultOAuthTokenIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>
}

export type $TokenVaultOAuthTokenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TokenVaultOAuthToken"
  objects: {
    account: Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    accountId: string
    clientId: string
    provider: string
    email: string
    ownerSub: string | null
    accessToken: string
    refreshToken: string | null
    tokenType: string | null
    expiresAt: Date | null
    scope: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tokenVaultOAuthToken"]>
  composites: {}
}

export type TokenVaultOAuthTokenGetPayload<S extends boolean | null | undefined | TokenVaultOAuthTokenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload, S>

export type TokenVaultOAuthTokenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TokenVaultOAuthTokenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TokenVaultOAuthTokenCountAggregateInputType | true
  }

export interface TokenVaultOAuthTokenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TokenVaultOAuthToken'], meta: { name: 'TokenVaultOAuthToken' } }
  /**
   * Find zero or one TokenVaultOAuthToken that matches the filter.
   * @param {TokenVaultOAuthTokenFindUniqueArgs} args - Arguments to find a TokenVaultOAuthToken
   * @example
   * // Get one TokenVaultOAuthToken
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TokenVaultOAuthTokenFindUniqueArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TokenVaultOAuthToken that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TokenVaultOAuthTokenFindUniqueOrThrowArgs} args - Arguments to find a TokenVaultOAuthToken
   * @example
   * // Get one TokenVaultOAuthToken
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TokenVaultOAuthTokenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TokenVaultOAuthToken that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenFindFirstArgs} args - Arguments to find a TokenVaultOAuthToken
   * @example
   * // Get one TokenVaultOAuthToken
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TokenVaultOAuthTokenFindFirstArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthTokenFindFirstArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TokenVaultOAuthToken that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenFindFirstOrThrowArgs} args - Arguments to find a TokenVaultOAuthToken
   * @example
   * // Get one TokenVaultOAuthToken
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TokenVaultOAuthTokenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthTokenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TokenVaultOAuthTokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TokenVaultOAuthTokens
   * const tokenVaultOAuthTokens = await prisma.tokenVaultOAuthToken.findMany()
   * 
   * // Get first 10 TokenVaultOAuthTokens
   * const tokenVaultOAuthTokens = await prisma.tokenVaultOAuthToken.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tokenVaultOAuthTokenWithIdOnly = await prisma.tokenVaultOAuthToken.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TokenVaultOAuthTokenFindManyArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthTokenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TokenVaultOAuthToken.
   * @param {TokenVaultOAuthTokenCreateArgs} args - Arguments to create a TokenVaultOAuthToken.
   * @example
   * // Create one TokenVaultOAuthToken
   * const TokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.create({
   *   data: {
   *     // ... data to create a TokenVaultOAuthToken
   *   }
   * })
   * 
   */
  create<T extends TokenVaultOAuthTokenCreateArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenCreateArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TokenVaultOAuthTokens.
   * @param {TokenVaultOAuthTokenCreateManyArgs} args - Arguments to create many TokenVaultOAuthTokens.
   * @example
   * // Create many TokenVaultOAuthTokens
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TokenVaultOAuthTokenCreateManyArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthTokenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TokenVaultOAuthTokens and returns the data saved in the database.
   * @param {TokenVaultOAuthTokenCreateManyAndReturnArgs} args - Arguments to create many TokenVaultOAuthTokens.
   * @example
   * // Create many TokenVaultOAuthTokens
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TokenVaultOAuthTokens and only return the `id`
   * const tokenVaultOAuthTokenWithIdOnly = await prisma.tokenVaultOAuthToken.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TokenVaultOAuthTokenCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthTokenCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TokenVaultOAuthToken.
   * @param {TokenVaultOAuthTokenDeleteArgs} args - Arguments to delete one TokenVaultOAuthToken.
   * @example
   * // Delete one TokenVaultOAuthToken
   * const TokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.delete({
   *   where: {
   *     // ... filter to delete one TokenVaultOAuthToken
   *   }
   * })
   * 
   */
  delete<T extends TokenVaultOAuthTokenDeleteArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenDeleteArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TokenVaultOAuthToken.
   * @param {TokenVaultOAuthTokenUpdateArgs} args - Arguments to update one TokenVaultOAuthToken.
   * @example
   * // Update one TokenVaultOAuthToken
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TokenVaultOAuthTokenUpdateArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenUpdateArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TokenVaultOAuthTokens.
   * @param {TokenVaultOAuthTokenDeleteManyArgs} args - Arguments to filter TokenVaultOAuthTokens to delete.
   * @example
   * // Delete a few TokenVaultOAuthTokens
   * const { count } = await prisma.tokenVaultOAuthToken.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TokenVaultOAuthTokenDeleteManyArgs>(args?: Prisma.SelectSubset<T, TokenVaultOAuthTokenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TokenVaultOAuthTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TokenVaultOAuthTokens
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TokenVaultOAuthTokenUpdateManyArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TokenVaultOAuthTokens and returns the data updated in the database.
   * @param {TokenVaultOAuthTokenUpdateManyAndReturnArgs} args - Arguments to update many TokenVaultOAuthTokens.
   * @example
   * // Update many TokenVaultOAuthTokens
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TokenVaultOAuthTokens and only return the `id`
   * const tokenVaultOAuthTokenWithIdOnly = await prisma.tokenVaultOAuthToken.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TokenVaultOAuthTokenUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TokenVaultOAuthToken.
   * @param {TokenVaultOAuthTokenUpsertArgs} args - Arguments to update or create a TokenVaultOAuthToken.
   * @example
   * // Update or create a TokenVaultOAuthToken
   * const tokenVaultOAuthToken = await prisma.tokenVaultOAuthToken.upsert({
   *   create: {
   *     // ... data to create a TokenVaultOAuthToken
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TokenVaultOAuthToken we want to update
   *   }
   * })
   */
  upsert<T extends TokenVaultOAuthTokenUpsertArgs>(args: Prisma.SelectSubset<T, TokenVaultOAuthTokenUpsertArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthTokenClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthTokenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TokenVaultOAuthTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenCountArgs} args - Arguments to filter TokenVaultOAuthTokens to count.
   * @example
   * // Count the number of TokenVaultOAuthTokens
   * const count = await prisma.tokenVaultOAuthToken.count({
   *   where: {
   *     // ... the filter for the TokenVaultOAuthTokens we want to count
   *   }
   * })
  **/
  count<T extends TokenVaultOAuthTokenCountArgs>(
    args?: Prisma.Subset<T, TokenVaultOAuthTokenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TokenVaultOAuthTokenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TokenVaultOAuthToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TokenVaultOAuthTokenAggregateArgs>(args: Prisma.Subset<T, TokenVaultOAuthTokenAggregateArgs>): Prisma.PrismaPromise<GetTokenVaultOAuthTokenAggregateType<T>>

  /**
   * Group by TokenVaultOAuthToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokenVaultOAuthTokenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TokenVaultOAuthTokenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TokenVaultOAuthTokenGroupByArgs['orderBy'] }
      : { orderBy?: TokenVaultOAuthTokenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TokenVaultOAuthTokenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTokenVaultOAuthTokenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TokenVaultOAuthToken model
 */
readonly fields: TokenVaultOAuthTokenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TokenVaultOAuthToken.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TokenVaultOAuthTokenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  account<T extends Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TokenVaultOAuthAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__TokenVaultOAuthAccountClient<runtime.Types.Result.GetResult<Prisma.$TokenVaultOAuthAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TokenVaultOAuthToken model
 */
export interface TokenVaultOAuthTokenFieldRefs {
  readonly id: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly accountId: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly clientId: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly provider: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly email: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly ownerSub: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly accessToken: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly refreshToken: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly tokenType: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly expiresAt: Prisma.FieldRef<"TokenVaultOAuthToken", 'DateTime'>
  readonly scope: Prisma.FieldRef<"TokenVaultOAuthToken", 'String'>
  readonly createdAt: Prisma.FieldRef<"TokenVaultOAuthToken", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TokenVaultOAuthToken", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TokenVaultOAuthToken findUnique
 */
export type TokenVaultOAuthTokenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthToken to fetch.
   */
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
}

/**
 * TokenVaultOAuthToken findUniqueOrThrow
 */
export type TokenVaultOAuthTokenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthToken to fetch.
   */
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
}

/**
 * TokenVaultOAuthToken findFirst
 */
export type TokenVaultOAuthTokenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthToken to fetch.
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthTokens to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthTokenOrderByWithRelationInput | Prisma.TokenVaultOAuthTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TokenVaultOAuthTokens.
   */
  cursor?: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenVaultOAuthTokens.
   */
  distinct?: Prisma.TokenVaultOAuthTokenScalarFieldEnum | Prisma.TokenVaultOAuthTokenScalarFieldEnum[]
}

/**
 * TokenVaultOAuthToken findFirstOrThrow
 */
export type TokenVaultOAuthTokenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthToken to fetch.
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthTokens to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthTokenOrderByWithRelationInput | Prisma.TokenVaultOAuthTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TokenVaultOAuthTokens.
   */
  cursor?: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenVaultOAuthTokens.
   */
  distinct?: Prisma.TokenVaultOAuthTokenScalarFieldEnum | Prisma.TokenVaultOAuthTokenScalarFieldEnum[]
}

/**
 * TokenVaultOAuthToken findMany
 */
export type TokenVaultOAuthTokenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * Filter, which TokenVaultOAuthTokens to fetch.
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TokenVaultOAuthTokens to fetch.
   */
  orderBy?: Prisma.TokenVaultOAuthTokenOrderByWithRelationInput | Prisma.TokenVaultOAuthTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TokenVaultOAuthTokens.
   */
  cursor?: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TokenVaultOAuthTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TokenVaultOAuthTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TokenVaultOAuthTokens.
   */
  distinct?: Prisma.TokenVaultOAuthTokenScalarFieldEnum | Prisma.TokenVaultOAuthTokenScalarFieldEnum[]
}

/**
 * TokenVaultOAuthToken create
 */
export type TokenVaultOAuthTokenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * The data needed to create a TokenVaultOAuthToken.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateInput, Prisma.TokenVaultOAuthTokenUncheckedCreateInput>
}

/**
 * TokenVaultOAuthToken createMany
 */
export type TokenVaultOAuthTokenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TokenVaultOAuthTokens.
   */
  data: Prisma.TokenVaultOAuthTokenCreateManyInput | Prisma.TokenVaultOAuthTokenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TokenVaultOAuthToken createManyAndReturn
 */
export type TokenVaultOAuthTokenCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * The data used to create many TokenVaultOAuthTokens.
   */
  data: Prisma.TokenVaultOAuthTokenCreateManyInput | Prisma.TokenVaultOAuthTokenCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TokenVaultOAuthToken update
 */
export type TokenVaultOAuthTokenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * The data needed to update a TokenVaultOAuthToken.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateInput>
  /**
   * Choose, which TokenVaultOAuthToken to update.
   */
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
}

/**
 * TokenVaultOAuthToken updateMany
 */
export type TokenVaultOAuthTokenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TokenVaultOAuthTokens.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateManyMutationInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateManyInput>
  /**
   * Filter which TokenVaultOAuthTokens to update
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * Limit how many TokenVaultOAuthTokens to update.
   */
  limit?: number
}

/**
 * TokenVaultOAuthToken updateManyAndReturn
 */
export type TokenVaultOAuthTokenUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * The data used to update TokenVaultOAuthTokens.
   */
  data: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateManyMutationInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateManyInput>
  /**
   * Filter which TokenVaultOAuthTokens to update
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * Limit how many TokenVaultOAuthTokens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TokenVaultOAuthToken upsert
 */
export type TokenVaultOAuthTokenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * The filter to search for the TokenVaultOAuthToken to update in case it exists.
   */
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
  /**
   * In case the TokenVaultOAuthToken found by the `where` argument doesn't exist, create a new TokenVaultOAuthToken with this data.
   */
  create: Prisma.XOR<Prisma.TokenVaultOAuthTokenCreateInput, Prisma.TokenVaultOAuthTokenUncheckedCreateInput>
  /**
   * In case the TokenVaultOAuthToken was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TokenVaultOAuthTokenUpdateInput, Prisma.TokenVaultOAuthTokenUncheckedUpdateInput>
}

/**
 * TokenVaultOAuthToken delete
 */
export type TokenVaultOAuthTokenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
  /**
   * Filter which TokenVaultOAuthToken to delete.
   */
  where: Prisma.TokenVaultOAuthTokenWhereUniqueInput
}

/**
 * TokenVaultOAuthToken deleteMany
 */
export type TokenVaultOAuthTokenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TokenVaultOAuthTokens to delete
   */
  where?: Prisma.TokenVaultOAuthTokenWhereInput
  /**
   * Limit how many TokenVaultOAuthTokens to delete.
   */
  limit?: number
}

/**
 * TokenVaultOAuthToken without action
 */
export type TokenVaultOAuthTokenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokenVaultOAuthToken
   */
  select?: Prisma.TokenVaultOAuthTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TokenVaultOAuthToken
   */
  omit?: Prisma.TokenVaultOAuthTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokenVaultOAuthTokenInclude<ExtArgs> | null
}
