name: 'PR Merged: Release, Deploy to GCP (GAE), Sync Env'
on:
  pull_request:
    paths-ignore:
    - '.github/**'
    types:
      - closed 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  create_release:
    #if: github.event.pull_request.merged == true
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
  
  # gcp_deploy:
  #   if: github.event.pull_request.merged == true && github.base_ref == 'master'
  #   needs: create_release
  #   name: Trigger Deploy to GCP App Engine 
  #   uses : nabarun-ngo/ngo-nabarun-templates/.github/workflows/Trigger-Workflow.yml@main
  #   with:
  #     repository: nabarun-ngo/ngo-nabarun-ops
  #     event_type: Trigger-Deploy-Sync-Test
  #     input_json: |-
  #       {
  #         "be_deploy": true ,
  #         "be_tag_name": "${{ needs.create_release.outputs.tag_name }}",
  #         "target_env": "stage",
  #         "auth0_sync" : ${{ contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'auth0') }},
  #         "run_smoke_test" : true
  #       }        


