name: 'PR Merged: Release, Deploy tp GCP (GAE), Sync Env'
on:
  pull_request:
    paths-ignore:
    - '.github/**'
    types:
      - closed 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
  
  gcp_deploy:
    if: github.event.pull_request.merged == true
    needs: create_release
    name: Deploy to GCP App Engine 
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/GCP-Deploy.yml@main
    with:
     tag_name: ${{ needs.create_release.outputs.tag_name }}
     target_folder: 'ngo-nabarun-app/target'
     gcp_project_id: ${{ github.base_ref == 'master' && vars.GCP_PROJECT_ID || vars.GCP_PROJECT_ID_STAGE }}
     app_env: ${{ github.base_ref == 'master' && 'prod' || 'stage' }}
     app_doppler_project_name: ${{ vars.DOPPLER_PROJECT_NAME }}
     app_log_level: ${{ github.base_ref == 'master' && 'INFO' || 'DEBUG' }}
    secrets:
      gcp_service_account: ${{ github.base_ref == 'master' && secrets.GCP_SERVICE_ACCOUNT || secrets.GCP_SERVICE_ACCOUNT_STAGE }}
      app_doppler_service_token: ${{ github.base_ref == 'master' && secrets.DOPPLER_SERVICE_TOKEN || secrets.DOPPLER_SERVICE_TOKEN_STAGE }}
  
  auth0_sync:
    if: github.event.pull_request.merged == true && (github.base_ref == 'master' || contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'Sync_Auth0'))
    needs: create_release
    name: Sync Auth0 Tenants 
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Auth0-Sync.yml@main
    with:
        branch_name: 'main'
        auth0_source_tenant: ${{ github.base_ref == 'master' && 'STAGE' || 'DEV' }}
        auth0_dest_tenant:  ${{ github.base_ref == 'master' && 'PROD' || 'STAGE' }}
    secrets:
        auth0_secrets: ${{ secrets.AUTH0_CREDENTIALS }}

  run_automated_test:
    if: github.event.pull_request.merged == true && always()
    needs: [gcp_deploy,auth0_sync]
    name: Run Smoke Test 
    uses: nabarun-ngo/ngo-nabarun-devops/.github/workflows/Run-Tests.yml@main
    with:
        test_env: ${{ github.base_ref == 'master' && 'PROD' || 'STAGE' }}
        test_doppler_project_name: 'nabarun_test'
        test_cycle: ${{ github.base_ref == 'master' && 'NAB-TR-3' || 'NAB-TR-1' }}
        upload_result: true 
        test_cucumber_tags: ${{ github.base_ref == 'master' && '@smokeprod' || '@smoke' }}
    secrets:
      test_doppler_service_token: ${{ github.base_ref == 'master' && secrets.DOPPLER_TEST_SERVICE_TOKEN || secrets.DOPPLER_TEST_SERVICE_TOKEN_STAGE }}
      qmetry_api_key: ${{ secrets.QMETRY_APIKEY }}
