name: 'PR Merged: Release, Deploy to GCP (GAE), Sync Env'
on:
  pull_request:
    paths-ignore:
    - '.github/**'
    types:
      - closed 
    branches:
    - master
    - stage

permissions:
  contents: write      

jobs:
  build:
   uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Build-Test.yml@main
   with:
      platform: "java"
      command: "./mvnw clean install"
      
  create_release:
    if: github.event.pull_request.merged == true
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
  
  gcp_deploy:
    if: github.event.pull_request.merged == true
    needs: create_release
    runs-on: ubuntu-latest
    name: Trigger Deploy to GCP App Engine 
    steps:
       - name: Repository Dispatch
         uses: peter-evans/repository-dispatch@v3
         with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.base_ref == 'master' && 'nabarun-ngo/ngo-nabarun-prodops' || 'nabarun-ngo/ngo-nabarun-ops' }}
          event-type: Trigger-Deploy-Sync-Test
          client-payload: |-
              {
                "be_deploy": true ,
                "be_tag_name": "${{ needs.create_release.outputs.tag_name }}",
                "target_env": "${{ github.base_ref == 'master' && 'prod' || 'stage' }}",
                "auth0_sync" : ${{ contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'auth0') }},
                "run_smoke_test" : true
              } 
